/*
 * Auto-generated by Sequencescape on 2025-08-08 12:35:56 +0100"
 * Using v14.75.2-16827067223-develop@062adb7
 * bundle exec rake devour:create_config"
 *
 * Reverted removal of tag2_group to prevent tests from failing
 */

/* Our configuration is essentially JSON, so we allow double quotes */
/* eslint quotes: ["error", "double"] */
const resources = [
  {
    "resource": "aliquot",
    "attributes": {
      "tag_oligo": "",
      "tag_index": "",
      "tag2_oligo": "",
      "tag2_index": "",
      "suboptimal": "",
      "library_type": "",
      "insert_size_to": "",
      "study": {
        "jsonApi": "hasOne",
        "type": "study"
      },
      "project": {
        "jsonApi": "hasOne",
        "type": "project"
      },
      "sample": {
        "jsonApi": "hasOne",
        "type": "sample"
      },
      "request": {
        "jsonApi": "hasOne",
        "type": "request"
      },
      "receptacle": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      },
      "tag": {
        "jsonApi": "hasOne",
        "type": "tag"
      },
      "tag2": {
        "jsonApi": "hasOne",
        "type": "tag"
      },
      "library": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      }
    },
    "options": {}
  },
  {
    "resource": "asset_audit",
    "attributes": {
      "key": "",
      "message": "",
      "created_by": "",
      "asset_uuid": "",
      "witnessed_by": "",
      "metadata": ""
    },
    "options": {}
  },
  {
    "resource": "asset",
    "attributes": {
      "uuid": "",
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      }
    },
    "options": {}
  },
  {
    "resource": "bait_library_layout",
    "attributes": {
      "plate_uuid": "",
      "user_uuid": "",
      "layout": "",
      "uuid": "",
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      },
      "plate": {
        "jsonApi": "hasOne",
        "type": "plate"
      }
    },
    "options": {}
  },
  {
    "resource": "barcode_printer",
    "attributes": {
      "name": "",
      "uuid": "",
      "print_service": "",
      "barcode_type": ""
    },
    "options": {}
  },
  {
    "resource": "bulk_transfer",
    "attributes": {
      "user_uuid": "",
      "uuid": "",
      "well_transfers": "",
      "transfers": {
        "jsonApi": "hasMany",
        "type": "transfer"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "comment",
    "attributes": {
      "title": "",
      "description": "",
      "created_at": "",
      "updated_at": "",
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      },
      "commentable": {
        "jsonApi": "hasOne"
      }
    },
    "options": {}
  },
  {
    "resource": "custom_metadatum_collection",
    "attributes": {
      "uuid": "",
      "user_id": "",
      "asset_id": "",
      "metadata": ""
    },
    "options": {}
  },
  {
    "resource": "faculty_sponsor",
    "attributes": {
      "name": ""
    },
    "options": {}
  },
  {
    "resource": "fragment",
    "attributes": {
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "labware",
    "attributes": {
      "uuid": "",
      "name": "",
      "labware_barcode": "",
      "state": "",
      "created_at": "",
      "updated_at": "",
      "retention_instruction": "",
      "purpose": {
        "jsonApi": "hasOne",
        "type": "purpose"
      },
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      },
      "qc_files": {
        "jsonApi": "hasMany",
        "type": "qc_file"
      },
      "receptacles": {
        "jsonApi": "hasMany"
      },
      "ancestors": {
        "jsonApi": "hasMany"
      },
      "descendants": {
        "jsonApi": "hasMany"
      },
      "parents": {
        "jsonApi": "hasMany"
      },
      "children": {
        "jsonApi": "hasMany"
      },
      "child_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "child_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "direct_submissions": {
        "jsonApi": "hasMany",
        "type": "submission"
      },
      "state_changes": {
        "jsonApi": "hasMany",
        "type": "state_change"
      }
    },
    "options": {}
  },
  {
    "resource": "lane",
    "attributes": {
      "uuid": "",
      "name": "",
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      }
    },
    "options": {}
  },
  {
    "resource": "lot_type",
    "attributes": {
      "uuid": "",
      "name": "",
      "template_type": "",
      "target_purpose": {
        "jsonApi": "hasOne",
        "type": "purpose"
      }
    },
    "options": {}
  },
  {
    "resource": "lot",
    "attributes": {
      "uuid": "",
      "lot_number": "",
      "lot_type": {
        "jsonApi": "hasOne",
        "type": "lot_type"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      },
      "template": {
        "jsonApi": "hasOne"
      },
      "tag_layout_template": {
        "jsonApi": "hasOne",
        "type": "tag_layout_template"
      }
    },
    "options": {}
  },
  {
    "resource": "order",
    "attributes": {
      "order_type": "",
      "request_options": "",
      "request_types": "",
      "uuid": "",
      "submission_template_uuid": "",
      "submission_template_attributes": "",
      "project": {
        "jsonApi": "hasOne",
        "type": "project"
      },
      "study": {
        "jsonApi": "hasOne",
        "type": "study"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "pick_list",
    "attributes": {
      "created_at": "",
      "updated_at": "",
      "state": "",
      "links": "",
      "pick_attributes": "",
      "labware_pick_attributes": "",
      "asynchronous": ""
    },
    "options": {}
  },
  {
    "resource": "plate_conversion",
    "attributes": {
      "parent_uuid": "",
      "purpose_uuid": "",
      "target_uuid": "",
      "user_uuid": "",
      "uuid": "",
      "parent": {
        "jsonApi": "hasOne",
        "type": "plate"
      },
      "purpose": {
        "jsonApi": "hasOne",
        "type": "plate_purpose"
      },
      "target": {
        "jsonApi": "hasOne",
        "type": "plate"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "plate_creation",
    "attributes": {
      "child_purpose_uuid": "",
      "parent_uuid": "",
      "user_uuid": "",
      "uuid": "",
      "child": {
        "jsonApi": "hasOne",
        "type": "plate"
      },
      "child_purpose": {
        "jsonApi": "hasOne",
        "type": "plate_purpose"
      },
      "parent": {
        "jsonApi": "hasOne",
        "type": "plate"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "plate_purpose",
    "attributes": {
      "name": "",
      "stock_plate": "",
      "cherrypickable_target": "",
      "input_plate": "",
      "size": "",
      "asset_shape": "",
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "plate_template",
    "attributes": {
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "plate",
    "attributes": {
      "uuid": "",
      "name": "",
      "labware_barcode": "",
      "state": "",
      "created_at": "",
      "updated_at": "",
      "retention_instruction": "",
      "number_of_rows": "",
      "number_of_columns": "",
      "size": "",
      "pooling_metadata": "",
      "purpose": {
        "jsonApi": "hasOne",
        "type": "purpose"
      },
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      },
      "qc_files": {
        "jsonApi": "hasMany",
        "type": "qc_file"
      },
      "receptacles": {
        "jsonApi": "hasMany"
      },
      "ancestors": {
        "jsonApi": "hasMany"
      },
      "descendants": {
        "jsonApi": "hasMany"
      },
      "parents": {
        "jsonApi": "hasMany"
      },
      "children": {
        "jsonApi": "hasMany"
      },
      "child_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "child_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "direct_submissions": {
        "jsonApi": "hasMany",
        "type": "submission"
      },
      "state_changes": {
        "jsonApi": "hasMany",
        "type": "state_change"
      },
      "submission_pools": {
        "jsonApi": "hasMany",
        "type": "submission_pool"
      },
      "transfers_as_destination": {
        "jsonApi": "hasMany",
        "type": "transfer"
      },
      "wells": {
        "jsonApi": "hasMany",
        "type": "well"
      }
    },
    "options": {}
  },
  {
    "resource": "poly_metadatum",
    "attributes": {
      "key": "",
      "value": "",
      "created_at": "",
      "updated_at": "",
      "metadatable": {
        "jsonApi": "hasOne"
      }
    },
    "options": {}
  },
  {
    "resource": "pooled_plate_creation",
    "attributes": {
      "child_purpose_uuid": "",
      "parent_uuids": "",
      "user_uuid": "",
      "uuid": "",
      "child": {
        "jsonApi": "hasOne",
        "type": "plate"
      },
      "parents": {
        "jsonApi": "hasMany",
        "type": "labware"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "pre_capture_pool",
    "attributes": {
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "primer_panel",
    "attributes": {
      "name": "",
      "programs": ""
    },
    "options": {}
  },
  {
    "resource": "project",
    "attributes": {
      "name": "",
      "cost_code": "",
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "purpose",
    "attributes": {
      "uuid": "",
      "name": "",
      "size": "",
      "lifespan": ""
    },
    "options": {}
  },
  {
    "resource": "qc_assay",
    "attributes": {
      "lot_number": "",
      "qc_results": {
        "jsonApi": "hasMany",
        "type": "qc_result"
      }
    },
    "options": {}
  },
  {
    "resource": "qc_file",
    "attributes": {
      "content_type": "",
      "created_at": "",
      "size": "",
      "uuid": "",
      "contents": "",
      "filename": "",
      "labware": {
        "jsonApi": "hasOne",
        "type": "labware"
      }
    },
    "options": {}
  },
  {
    "resource": "qc_result",
    "attributes": {
      "key": "",
      "value": "",
      "units": "",
      "cv": "",
      "assay_type": "",
      "assay_version": "",
      "created_at": "",
      "asset": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      }
    },
    "options": {}
  },
  {
    "resource": "qcable",
    "attributes": {
      "labware_barcode": "",
      "state": "",
      "uuid": "",
      "asset": {
        "jsonApi": "hasOne",
        "type": "labware"
      },
      "labware": {
        "jsonApi": "hasOne",
        "type": "labware"
      },
      "lot": {
        "jsonApi": "hasOne",
        "type": "lot"
      }
    },
    "options": {}
  },
  {
    "resource": "racked_tube",
    "attributes": {
      "coordinate": "",
      "tube": {
        "jsonApi": "hasOne",
        "type": "tube"
      },
      "tube_rack": {
        "jsonApi": "hasOne",
        "type": "tube_rack"
      }
    },
    "options": {}
  },
  {
    "resource": "receptacle",
    "attributes": {
      "uuid": "",
      "name": "",
      "pcr_cycles": "",
      "submit_for_sequencing": "",
      "sub_pool": "",
      "coverage": "",
      "diluent_volume": "",
      "state": "",
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "requests_as_source": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "requests_as_target": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "qc_results": {
        "jsonApi": "hasMany",
        "type": "qc_result"
      },
      "aliquots": {
        "jsonApi": "hasMany",
        "type": "aliquot"
      },
      "downstream_assets": {
        "jsonApi": "hasMany"
      },
      "downstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "downstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "downstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "upstream_assets": {
        "jsonApi": "hasMany"
      },
      "upstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "upstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "upstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "transfer_requests_as_source": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      },
      "transfer_requests_as_target": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      },
      "labware": {
        "jsonApi": "hasOne",
        "type": "labware"
      }
    },
    "options": {}
  },
  {
    "resource": "request_metadata",
    "attributes": {
      "number_of_pools": "",
      "cells_per_chip_well": "",
      "allowance_band": "",
      "request": {
        "jsonApi": "hasOne",
        "type": "request"
      }
    },
    "options": {}
  },
  {
    "resource": "request_type",
    "attributes": {
      "uuid": "",
      "name": "",
      "key": "",
      "for_multiplexing": "",
      "requests": {
        "jsonApi": "hasMany",
        "type": "request"
      }
    },
    "options": {}
  },
  {
    "resource": "request",
    "attributes": {
      "uuid": "",
      "role": "",
      "state": "",
      "priority": "",
      "options": "",
      "library_type": "",
      "submission": {
        "jsonApi": "hasOne",
        "type": "submission"
      },
      "order": {
        "jsonApi": "hasOne",
        "type": "order"
      },
      "request_type": {
        "jsonApi": "hasOne",
        "type": "request_type"
      },
      "primer_panel": {
        "jsonApi": "hasOne",
        "type": "primer_panel"
      },
      "pre_capture_pool": {
        "jsonApi": "hasOne",
        "type": "pre_capture_pool"
      },
      "poly_metadata": {
        "jsonApi": "hasMany",
        "type": "poly_metadatum"
      },
      "request_metadata": {
        "jsonApi": "hasOne",
        "type": "request_metadata"
      }
    },
    "options": {}
  },
  {
    "resource": "sample_manifest",
    "attributes": {
      "supplier_name": ""
    },
    "options": {}
  },
  {
    "resource": "sample_metadata",
    "attributes": {
      "cohort": "",
      "collected_by": "",
      "date_of_sample_collection": "",
      "concentration": "",
      "donor_id": "",
      "gender": "",
      "sample_common_name": "",
      "sample_description": "",
      "supplier_name": "",
      "volume": ""
    },
    "options": {}
  },
  {
    "resource": "sample",
    "attributes": {
      "name": "",
      "sanger_sample_id": "",
      "uuid": "",
      "control": "",
      "control_type": "",
      "sample_metadata": {
        "jsonApi": "hasOne",
        "type": "sample_metadata"
      },
      "sample_manifest": {
        "jsonApi": "hasOne",
        "type": "sample_manifest"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "component_samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      }
    },
    "options": {}
  },
  {
    "resource": "specific_tube_creation",
    "attributes": {
      "uuid": "",
      "child_purpose_uuids": "",
      "parent_uuids": "",
      "tube_attributes": "",
      "user_uuid": "",
      "children": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "parents": {
        "jsonApi": "hasMany",
        "type": "labware"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "specific_tube_rack_creation",
    "attributes": {
      "parent_uuids": "",
      "tube_rack_attributes": "",
      "user_uuid": "",
      "uuid": "",
      "children": {
        "jsonApi": "hasMany",
        "type": "tube_rack"
      },
      "parents": {
        "jsonApi": "hasMany",
        "type": "labware"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "state_change",
    "attributes": {
      "contents": "",
      "customer_accepts_responsibility": "",
      "previous_state": "",
      "reason": "",
      "target_state": "",
      "target_uuid": "",
      "user_uuid": "",
      "uuid": "",
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      },
      "target": {
        "jsonApi": "hasOne",
        "type": "labware"
      }
    },
    "options": {}
  },
  {
    "resource": "study",
    "attributes": {
      "name": "",
      "uuid": "",
      "poly_metadata": {
        "jsonApi": "hasMany",
        "type": "poly_metadatum"
      },
      "study_metadata": {
        "jsonApi": "hasOne",
        "type": "study_metadata"
      }
    },
    "options": {}
  },
  {
    "resource": "study_metadata",
    "attributes": {
      "faculty_sponsor": {
        "jsonApi": "hasOne",
        "type": "faculty_sponsor"
      }
    },
    "options": {}
  },
  {
    "resource": "submission_pool",
    "attributes": {
      "plates_in_submission": "",
      "tag_layout_templates": {
        "jsonApi": "hasMany",
        "type": "tag_layout_template"
      }
    },
    "options": {}
  },
  {
    "resource": "submission_template",
    "attributes": {
      "uuid": "",
      "name": ""
    },
    "options": {}
  },
  {
    "resource": "submission",
    "attributes": {
      "created_at": "",
      "updated_at": "",
      "lanes_of_sequencing": "",
      "multiplexed?": "",
      "and_submit": "",
      "name": "",
      "order_uuids": "",
      "state": "",
      "used_tags": "",
      "user_uuid": "",
      "uuid": "",
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      },
      "orders": {
        "jsonApi": "hasMany",
        "type": "order"
      }
    },
    "options": {}
  },
  {
    "resource": "tag_group_adapter_type",
    "attributes": {
      "name": "",
      "tag_groups": {
        "jsonApi": "hasMany",
        "type": "tag_group"
      }
    },
    "options": {}
  },
  {
    "resource": "tag_group",
    "attributes": {
      "uuid": "",
      "name": "",
      "tags": "",
      "tag_group_adapter_type": {
        "jsonApi": "hasOne",
        "type": "tag_group_adapter_type"
      }
    },
    "options": {}
  },
  {
    "resource": "tag2_group",
    "attributes": {
      "uuid": "",
      "name": "",
      "tags": "",
      "tag_group_adapter_type": {
        "jsonApi": "hasOne",
        "type": "tag_group_adapter_type"
      }
    },
    "options": {
    }
  },
  {
    "resource": "tag_layout_template",
    "attributes": {
      "uuid": "",
      "name": "",
      "direction": "",
      "walking_by": "",
      "tag_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      },
      "tag2_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      }
    },
    "options": {}
  },
  {
    "resource": "tag_layout",
    "attributes": {
      "direction": "",
      "initial_tag": "",
      "plate_uuid": "",
      "substitutions": "",
      "tag_group_uuid": "",
      "tag2_group_uuid": "",
      "tags_per_well": "",
      "user_uuid": "",
      "uuid": "",
      "walking_by": "",
      "tag_layout_template_uuid": "",
      "enforce_uniqueness": "",
      "plate": {
        "jsonApi": "hasOne",
        "type": "plate"
      },
      "tag_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      },
      "tag2_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "tag_set",
    "attributes": {
      "uuid": "",
      "name": "",
      "tag_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      },
      "tag2_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      }
    },
    "options": {}
  },
  {
    "resource": "tag",
    "attributes": {
      "map_id": "",
      "oligo": "",
      "tag_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      }
    },
    "options": {}
  },
  {
    "resource": "template",
    "attributes": {},
    "options": {}
  },
  {
    "resource": "transfer_request_collection",
    "attributes": {
      "transfer_requests_attributes": "",
      "user_uuid": "",
      "uuid": "",
      "target_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "transfer_requests": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "transfer_request",
    "attributes": {
      "uuid": "",
      "state": "",
      "volume": "",
      "source_asset": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      },
      "submission": {
        "jsonApi": "hasOne",
        "type": "submission"
      },
      "target_asset": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      }
    },
    "options": {}
  },
  {
    "resource": "transfer_template",
    "attributes": {
      "name": "",
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "transfer",
    "attributes": {
      "uuid": "",
      "transfers": "",
      "transfer_type": "",
      "transfer_template_uuid": "",
      "destination_uuid": "",
      "source_uuid": "",
      "user_uuid": "",
      "destination": {
        "jsonApi": "hasOne",
        "type": "labware"
      },
      "source": {
        "jsonApi": "hasOne",
        "type": "labware"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "tube_from_plate_creation",
    "attributes": {
      "child_purpose_uuid": "",
      "parent_uuid": "",
      "user_uuid": "",
      "uuid": "",
      "child": {
        "jsonApi": "hasOne",
        "type": "tube"
      },
      "child_purpose": {
        "jsonApi": "hasOne",
        "type": "tube_purpose"
      },
      "parent": {
        "jsonApi": "hasOne",
        "type": "plate"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "tube_from_tube_creation",
    "attributes": {
      "child_purpose_uuid": "",
      "parent_uuid": "",
      "user_uuid": "",
      "uuid": "",
      "child": {
        "jsonApi": "hasOne",
        "type": "tube"
      },
      "child_purpose": {
        "jsonApi": "hasOne",
        "type": "tube_purpose"
      },
      "parent": {
        "jsonApi": "hasOne",
        "type": "tube"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "tube_purpose",
    "attributes": {
      "name": "",
      "purpose_type": "",
      "target_type": "",
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "tube_rack_purpose",
    "attributes": {
      "name": "",
      "size": "",
      "purpose_type": "",
      "target_type": "",
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "tube_rack_status",
    "attributes": {
      "uuid": ""
    },
    "options": {}
  },
  {
    "resource": "tube_rack",
    "attributes": {
      "created_at": "",
      "labware_barcode": "",
      "name": "",
      "number_of_columns": "",
      "number_of_rows": "",
      "size": "",
      "tube_locations": "",
      "updated_at": "",
      "uuid": "",
      "state": "",
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      },
      "racked_tubes": {
        "jsonApi": "hasMany",
        "type": "racked_tube"
      },
      "purpose": {
        "jsonApi": "hasOne",
        "type": "tube_rack_purpose"
      },
      "parents": {
        "jsonApi": "hasMany"
      },
      "state_changes": {
        "jsonApi": "hasMany",
        "type": "state_change"
      },
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "ancestors": {
        "jsonApi": "hasMany"
      },
      "tube_receptacles": {
        "jsonApi": "hasMany",
        "type": "receptacle"
      }
    },
    "options": {}
  },
  {
    "resource": "tube",
    "attributes": {
      "uuid": "",
      "name": "",
      "labware_barcode": "",
      "state": "",
      "created_at": "",
      "updated_at": "",
      "retention_instruction": "",
      "sibling_tubes": "",
      "purpose": {
        "jsonApi": "hasOne",
        "type": "purpose"
      },
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      },
      "qc_files": {
        "jsonApi": "hasMany",
        "type": "qc_file"
      },
      "receptacles": {
        "jsonApi": "hasMany"
      },
      "ancestors": {
        "jsonApi": "hasMany"
      },
      "descendants": {
        "jsonApi": "hasMany"
      },
      "parents": {
        "jsonApi": "hasMany"
      },
      "children": {
        "jsonApi": "hasMany"
      },
      "child_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "child_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "direct_submissions": {
        "jsonApi": "hasMany",
        "type": "submission"
      },
      "state_changes": {
        "jsonApi": "hasMany",
        "type": "state_change"
      },
      "aliquots": {
        "jsonApi": "hasMany",
        "type": "aliquot"
      },
      "receptacle": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      },
      "transfer_requests_as_target": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      },
      "racked_tube": {
        "jsonApi": "hasOne",
        "type": "racked_tube"
      }
    },
    "options": {}
  },
  {
    "resource": "user",
    "attributes": {
      "uuid": "",
      "login": "",
      "first_name": "",
      "last_name": ""
    },
    "options": {}
  },
  {
    "resource": "volume_update",
    "attributes": {
      "created_by": "",
      "target_uuid": "",
      "volume_change": ""
    },
    "options": {}
  },
  {
    "resource": "well",
    "attributes": {
      "uuid": "",
      "name": "",
      "pcr_cycles": "",
      "submit_for_sequencing": "",
      "sub_pool": "",
      "coverage": "",
      "diluent_volume": "",
      "state": "",
      "position": "",
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "requests_as_source": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "requests_as_target": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "qc_results": {
        "jsonApi": "hasMany",
        "type": "qc_result"
      },
      "aliquots": {
        "jsonApi": "hasMany",
        "type": "aliquot"
      },
      "downstream_assets": {
        "jsonApi": "hasMany"
      },
      "downstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "downstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "downstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "upstream_assets": {
        "jsonApi": "hasMany"
      },
      "upstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "upstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "upstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "transfer_requests_as_source": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      },
      "transfer_requests_as_target": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      },
      "labware": {
        "jsonApi": "hasOne",
        "type": "labware"
      },
      "poly_metadata": {
        "jsonApi": "hasMany",
        "type": "poly_metadatum"
      }
    },
    "options": {}
  },
  {
    "resource": "work_completion",
    "attributes": {
      "submission_uuids": "",
      "target_uuid": "",
      "user_uuid": "",
      "submissions": {
        "jsonApi": "hasMany",
        "type": "submission"
      },
      "target": {
        "jsonApi": "hasOne",
        "type": "labware"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      }
    },
    "options": {}
  },
  {
    "resource": "work_order",
    "attributes": {
      "at_risk": "",
      "options": "",
      "order_type": "",
      "quantity": "",
      "state": "",
      "study": {
        "jsonApi": "hasOne",
        "type": "study"
      },
      "project": {
        "jsonApi": "hasOne",
        "type": "project"
      },
      "source_receptacle": {
        "jsonApi": "hasOne"
      },
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      }
    },
    "options": {}
  }
]

export default resources
