---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: false
  RequireInputAutocomplete:
    enabled: false
  SelfClosingTag:
    enabled: false
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      # Recommended settings from erb_lint
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false

      # This rule removes the "<%" and "<%="  from the code, if enabled
      Layout/LeadingEmptyLines:
        Enabled: false
