inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
Style/VariableNumber:
  Enabled: false
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/robots.rb
