inherit_from:
  - .rubocop_todo.yml
  - node_modules/@prettier/plugin-ruby/rubocop.yml
plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - node_modules/**/*
    - bin/**/*
    - vendor/**/*
  NewCops: enable
Rails:
  Enabled: true
# We're not actually using Rails methods here.
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/FindBy:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false

# Only use shorthand hash syntax when all keys match the variables for better readability
Style/HashSyntax:
  EnforcedShorthandSyntax: consistent

# Filter out all the DSLs
Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  AllowedMethods:
    - describe
    - context
    - background
    - scenario
    - namespace
    - task
    - included
    - shared_context
    - shared_examples
    - state_machine
    - configure
    - draw
    - feature
    - subject
    - let
    - let!
    - factory
    - define
    - guard
    - transient
    - it
  Exclude:
    - config/robots.rb
Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Naming/VariableNumber:
  CheckSymbols:
    false # Rubocop gets annoyed about our states. I'm disabling globally
    # as I'm honestly not that bothered.

RSpec/ContextWording:
  Prefixes:
    - for
    - if
    - unless
    - when
    - where
    - with
    - without

RSpec/DescribeClass:
  # Exclude files like exports that do not have a specific class.
  Exclude:
    - spec/factory_outputs/**/*.rb
    - spec/views/**/*exports/**/*.rb

RSpec/DescribedClass:
  EnforcedStyle: described_class
  SkipBlocks: true # Addresses a known caveat with rspec-rails’s ‘controller` helper that runs its
  # block in a different context

RSpec/ExampleLength:
  inherit_mode:
    merge:
      - Exclude
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  # Disable for features, as we might want to step through long processes
  Exclude:
    - 'spec/features/**/*'

RSpec/IndexedLet:
  Enabled: false # We have a lot of indexed lets in our specs, mostly based on wells or racked tubes

RSpec/LetBeforeExamples:
  Enabled: false # It can be helpful to have the let variables just before the relevant example

RSpec/ScatteredLet:
  Enabled: false # Disabling due to scattered lets not being such a big deal and the automated fix
  # being unreliable (see https://github.com/rubocop/rubocop-rspec/issues/1167).

RSpec/MultipleMemoizedHelpers:
  Enabled: false # We have a lot of memoized helpers in our specs, not sure how best to work around this, so disabling

RSpec/NestedGroups:
  Max: 5 # Default is 3, but we have a lot of nested groups in our specs

RSpec/NamedSubject:
  EnforcedStyle: named_only
