version: "3.3"
services:
  limber:
    build: .
    image: rails_app
    ports:
      - "3001:3001"
    environment:
      - GENERATE_CONFIG=$GENERATE_CONFIG
      - LOCALHOST=host.docker.internal
    volumes:
      - ".:/code"
