version: '3.3'
services:
  limber:
    build:
      context: .
      args:
        bundlerWithout: '' # Don't exclude development groups
        yarnFlags: '' # Don't exclude devDependencies
    ports:
      - '3001:3001'
    environment:
      - GENERATE_CONFIG=${GENERATE_CONFIG:-true}
      - LOCALHOST=host.docker.internal
    volumes:
      - '.:/code'
