/*
 * Auto-generated by Sequencescape on 2019-07-15 14:21:33 +0100"
 * Using hotfix_live_testing_errors@eacc622
 * bundle exec rake devour:create_config"
 *
 */

/* Our configuration is essentially JSON, so we allow double quotes */
/* eslint quotes: ["error", "double"] */
const resources = [
  {
    "resource": "aliquot",
    "attributes": {
      "tag_oligo": "",
      "tag_index": "",
      "tag2_oligo": "",
      "tag2_index": "",
      "suboptimal": "",
      "sample": {
        "jsonApi": "hasOne",
        "type": "sample"
      },
      "request": {
        "jsonApi": "hasOne",
        "type": "request"
      }
    },
    "options": {
    }
  },
  {
    "resource": "asset",
    "attributes": {
      "uuid": "",
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      }
    },
    "options": {
    }
  },
  {
    "resource": "comment",
    "attributes": {
      "title": "",
      "description": "",
      "created_at": "",
      "updated_at": "",
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      },
      "commentable": {
        "jsonApi": "hasOne"
      }
    },
    "options": {
    }
  },
  {
    "resource": "custom_metadatum_collection",
    "attributes": {
      "uuid": "",
      "metadata": ""
    },
    "options": {
    }
  },
  {
    "resource": "labware",
    "attributes": {
      "uuid": "",
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      }
    },
    "options": {
    }
  },
  {
    "resource": "lane",
    "attributes": {
      "uuid": "",
      "name": "",
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      }
    },
    "options": {
    }
  },
  {
    "resource": "lot",
    "attributes": {
      "uuid": "",
      "lot_number": "",
      "lot_type": {
        "jsonApi": "hasOne",
        "type": "lot_type"
      },
      "user": {
        "jsonApi": "hasOne",
        "type": "user"
      },
      "template": {
        "jsonApi": "hasOne"
      },
      "tag_layout_template": {
        "jsonApi": "hasOne",
        "type": "tag_layout_template"
      }
    },
    "options": {
    }
  },
  {
    "resource": "lot_type",
    "attributes": {
      "uuid": "",
      "name": "",
      "template_type": "",
      "target_purpose": {
        "jsonApi": "hasOne",
        "type": "purpose"
      }
    },
    "options": {
    }
  },
  {
    "resource": "order",
    "attributes": {
      "uuid": ""
    },
    "options": {
    }
  },
  {
    "resource": "plate",
    "attributes": {
      "uuid": "",
      "name": "",
      "labware_barcode": "",
      "state": "",
      "number_of_rows": "",
      "number_of_columns": "",
      "created_at": "",
      "updated_at": "",
      "purpose": {
        "jsonApi": "hasOne",
        "type": "purpose"
      },
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      },
      "ancestors": {
        "jsonApi": "hasMany"
      },
      "descendants": {
        "jsonApi": "hasMany"
      },
      "parents": {
        "jsonApi": "hasMany"
      },
      "children": {
        "jsonApi": "hasMany"
      },
      "child_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "child_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      }
    },
    "options": {
    }
  },
  {
    "resource": "plate_template",
    "attributes": {
      "uuid": ""
    },
    "options": {
    }
  },
  {
    "resource": "pre_capture_pool",
    "attributes": {
      "uuid": ""
    },
    "options": {
    }
  },
  {
    "resource": "primer_panel",
    "attributes": {
      "name": "",
      "programs": ""
    },
    "options": {
    }
  },
  {
    "resource": "project",
    "attributes": {
      "name": "",
      "cost_code": "",
      "uuid": ""
    },
    "options": {
    }
  },
  {
    "resource": "purpose",
    "attributes": {
      "uuid": "",
      "name": ""
    },
    "options": {
    }
  },
  {
    "resource": "qc_assay",
    "attributes": {
      "lot_number": "",
      "qc_results": {
        "jsonApi": "hasMany",
        "type": "qc_result"
      }
    },
    "options": {
    }
  },
  {
    "resource": "qc_result",
    "attributes": {
      "key": "",
      "value": "",
      "units": "",
      "cv": "",
      "assay_type": "",
      "assay_version": "",
      "created_at": "",
      "asset": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      }
    },
    "options": {
    }
  },
  {
    "resource": "qcable",
    "attributes": {
      "uuid": "",
      "state": "",
      "labware_barcode": "",
      "lot": {
        "jsonApi": "hasOne",
        "type": "lot"
      },
      "asset": {
        "jsonApi": "hasOne"
      }
    },
    "options": {
    }
  },
  {
    "resource": "receptacle",
    "attributes": {
      "uuid": "",
      "name": "",
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "requests_as_source": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "requests_as_target": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "aliquots": {
        "jsonApi": "hasMany",
        "type": "aliquot"
      },
      "downstream_assets": {
        "jsonApi": "hasMany"
      },
      "downstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "downstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "downstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "upstream_assets": {
        "jsonApi": "hasMany"
      },
      "upstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "upstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "upstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      }
    },
    "options": {
    }
  },
  {
    "resource": "request",
    "attributes": {
      "uuid": "",
      "role": "",
      "state": "",
      "priority": "",
      "options": "",
      "submission": {
        "jsonApi": "hasOne",
        "type": "submission"
      },
      "order": {
        "jsonApi": "hasOne",
        "type": "order"
      },
      "request_type": {
        "jsonApi": "hasOne",
        "type": "request_type"
      },
      "primer_panel": {
        "jsonApi": "hasOne",
        "type": "primer_panel"
      },
      "pre_capture_pool": {
        "jsonApi": "hasOne",
        "type": "pre_capture_pool"
      }
    },
    "options": {
    }
  },
  {
    "resource": "request_type",
    "attributes": {
      "uuid": "",
      "name": "",
      "key": "",
      "for_multiplexing": ""
    },
    "options": {
    }
  },
  {
    "resource": "sample_metadata",
    "attributes": {
      "sample_common_name": ""
    },
    "options": {
    }
  },
  {
    "resource": "sample",
    "attributes": {
      "name": "",
      "sanger_sample_id": "",
      "uuid": "",
      "sample_metadata": {
        "jsonApi": "hasOne",
        "type": "sample_metadata"
      }
    },
    "options": {
    }
  },
  {
    "resource": "study",
    "attributes": {
      "name": "",
      "uuid": ""
    },
    "options": {
    }
  },
  {
    "resource": "submission",
    "attributes": {
      "uuid": "",
      "name": "",
      "used_tags": ""
    },
    "options": {
    }
  },
  {
    "resource": "tag_group",
    "attributes": {
      "uuid": "",
      "name": "",
      "tags": ""
    },
    "options": {
    }
  },
  {
    "resource": "tag_layout_template",
    "attributes": {
      "uuid": "",
      "direction": "",
      "walking_by": "",
      "tag_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      },
      "tag2_group": {
        "jsonApi": "hasOne",
        "type": "tag_group"
      }
    },
    "options": {
    }
  },
  {
    "resource": "transfer_request",
    "attributes": {
      "uuid": "",
      "state": "",
      "volume": "",
      "target_asset": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      },
      "source_asset": {
        "jsonApi": "hasOne",
        "type": "receptacle"
      },
      "submission": {
        "jsonApi": "hasOne",
        "type": "submission"
      }
    },
    "options": {
    }
  },
  {
    "resource": "tube",
    "attributes": {
      "uuid": "",
      "name": "",
      "labware_barcode": "",
      "state": "",
      "created_at": "",
      "updated_at": "",
      "purpose": {
        "jsonApi": "hasOne",
        "type": "purpose"
      },
      "custom_metadatum_collection": {
        "jsonApi": "hasOne",
        "type": "custom_metadatum_collection"
      },
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "aliquots": {
        "jsonApi": "hasMany",
        "type": "aliquot"
      },
      "ancestors": {
        "jsonApi": "hasMany"
      },
      "descendants": {
        "jsonApi": "hasMany"
      },
      "parents": {
        "jsonApi": "hasMany"
      },
      "children": {
        "jsonApi": "hasMany"
      },
      "comments": {
        "jsonApi": "hasMany",
        "type": "comment"
      }
    },
    "options": {
    }
  },
  {
    "resource": "user",
    "attributes": {
      "uuid": "",
      "login": "",
      "first_name": "",
      "last_name": ""
    },
    "options": {
    }
  },
  {
    "resource": "well",
    "attributes": {
      "uuid": "",
      "name": "",
      "position": "",
      "state": "",
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      },
      "studies": {
        "jsonApi": "hasMany",
        "type": "study"
      },
      "projects": {
        "jsonApi": "hasMany",
        "type": "project"
      },
      "qc_results": {
        "jsonApi": "hasMany",
        "type": "qc_result"
      },
      "requests_as_source": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "requests_as_target": {
        "jsonApi": "hasMany",
        "type": "request"
      },
      "aliquots": {
        "jsonApi": "hasMany",
        "type": "aliquot"
      },
      "downstream_assets": {
        "jsonApi": "hasMany"
      },
      "downstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "downstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "downstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "upstream_assets": {
        "jsonApi": "hasMany"
      },
      "upstream_wells": {
        "jsonApi": "hasMany",
        "type": "well"
      },
      "upstream_plates": {
        "jsonApi": "hasMany",
        "type": "plate"
      },
      "upstream_tubes": {
        "jsonApi": "hasMany",
        "type": "tube"
      },
      "transfer_requests_as_source": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      },
      "transfer_requests_as_target": {
        "jsonApi": "hasMany",
        "type": "transfer_request"
      }
    },
    "options": {
    }
  },
  {
    "resource": "work_order",
    "attributes": {
      "order_type": "",
      "quantity": "",
      "state": "",
      "options": "",
      "at_risk": "",
      "study": {
        "jsonApi": "hasOne",
        "type": "study"
      },
      "project": {
        "jsonApi": "hasOne",
        "type": "project"
      },
      "source_receptacle": {
        "jsonApi": "hasOne"
      },
      "samples": {
        "jsonApi": "hasMany",
        "type": "sample"
      }
    },
    "options": {
    }
  }
]

export default resources
