# ANOSPP plate purposes
---
# Entry point plate created by sample manifest for insect in ethanol plates
LANS-96 Stock:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: false
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
  :creator_class: LabwareCreators::Uncreatable
  :size: 96
# LANS-96 Lysate plate is the end result of lysis prep and the start of library prep.
# Once this plate is made we want to close off the lysate prep submission requests,
# and we use the AutomaticPlateStateChanger for this.
LANS-96 Lysate:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :label_template: plate_96_lysate
  :presenter_class: Presenters::StockPlatePresenter
  :state_changer_class: StateChangers::AutomaticPlateStateChanger
  :work_completion_request_type: 'limber_anospp_lysate_prep'
  :size: 96
