---
# BGE Pipeline Purposes
# 'Limber-Htp - BGE PCR Free' manual submission is on BGE Cherrypick
BGE Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
BGE Shear:
  :asset_type: plate
BGE Post Shear:
  :asset_type: plate
BGE End Prep:
  :asset_type: plate
BGE Lib:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
    - 'IDT for Illumina UDI v1'
    - 'IDT for Illumina UDI v2'
    - 'NEXTflex-96 barcoded adapters tags in rows (first oligo: AACGTGAT)'
    - 'PF_adapters_UDI_96_A'
    - 'PF_adapters_UDI_96_B_ROWS'
    - 'PF_adapters_UDI_96_B'
    - 'PF_adapters_UDI_96_C'
    - 'PF_adapters_UDI_96_D'
# 'Limber-Htp - BGE Transition - Automated' submission is on BGE Lib XP2
BGE Lib XP2:
  :asset_type: plate
  :presenter_class: Presenters::PermissiveSubmissionPlatePresenter
  :submission_options:
    BGE Transition - Automated:
      template_name: 'Limber-Htp - BGE Transition - Automated'
      request_options:
        fragment_size_required_from: '450'
        fragment_size_required_to: '450'
      allowed_extra_barcodes: false
BGE Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
BGE Lib PCR:
  :asset_type: plate
# 'Limber-Htp - BGE ISC' manual submission is on BGE Lib PCR XP
BGE Lib PCR XP:
  :asset_type: plate
BGE Lib PrePool:
  :asset_type: plate
BGE Hyb:
  :asset_type: plate
BGE Cap Lib:
  :asset_type: plate
BGE Cap Lib PCR:
  :asset_type: plate
BGE Cap PCR XP:
  :asset_type: plate
BGE Cap Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
BGE Cap Lib Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::SimpleTubePresenter
BGE Blended Cap Lib Pool:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesFromWholeTubes
  :presenter_class: Presenters::SimpleTubePresenter
BGE Custom pool:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::SimpleTubePresenter
