---
CLCM Stock:
  :asset_type: plate
  :stock_plate: true
  :input_plate: true
  :creator_class: LabwareCreators::Uncreatable
CLCM Lysate DNA:
  :asset_type: plate
  :creator_class:
    name: LabwareCreators::MultiStampLibrarySplitter
    args: &library_type_splitting_config
      default_volume: 25
      library_type_split_plate_purpose:
        - library_type: Combined LCM DNA
          plate_purpose: CLCM Lysate DNA
        - library_type: Combined LCM RNA
          plate_purpose: CLCM Lysate RNA
  :transfer_library_type: Combined LCM DNA
CLCM DNA End Prep:
  :asset_type: plate
CLCM DNA Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
    - Illumina pipeline tagging
    - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
    - hWGS and RNAseq UDI tag layout v3
    - pWGS UDI tag layout v2 A
    - pWGS UDI tag layout v2 B
    - pWGS UDI tag layout v2 C
    - pWGS UDI tag layout v2 D
    - TS_pWGSA_UDI96
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSD_UDI96
    - TSRNAhWGS_UDI96
    - TS_pWGSA_UDI96v2
    - TSISC_UDI96
CLCM DNA Lib PCR XP:
  :asset_type: plate
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :file_links:
    - name: Download Concentration (nM) CSV
      id: concentrations_nm
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
CLCM DNA Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::CustomPooledTubes
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
CLCM DNA Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::FinalTubePresenter
  :default_printer_type: :tube
CLCM Lysate RNA:
  :asset_type: plate
  :creator_class:
    name: LabwareCreators::MultiStampLibrarySplitter
    args: *library_type_splitting_config
  :transfer_library_type: Combined LCM RNA
CLCM RT PreAmp:
  :asset_type: plate
CLCM RNA End Prep:
  :asset_type: plate
CLCM RNA Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
    - Illumina pipeline tagging
    - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
    - hWGS and RNAseq UDI tag layout v3
    - pWGS UDI tag layout v2 A
    - pWGS UDI tag layout v2 B
    - pWGS UDI tag layout v2 C
    - pWGS UDI tag layout v2 D
    - TS_pWGSA_UDI96
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSD_UDI96
    - TSRNAhWGS_UDI96
    - TS_pWGSA_UDI96v2
    - TSISC_UDI96
CLCM RNA Lib PCR XP:
  :asset_type: plate
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :file_links:
    - name: Download Concentration (nM) CSV
      id: concentrations_nm
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
CLCM RNA Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::CustomPooledTubes
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
CLCM RNA Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::FinalTubePresenter
  :default_printer_type: :tube
