# RVI Cherrypick is the first plate in this pipeline but it is already defined in the rvi.yml file.

RVIG RT:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter

RVIG cDNA XP:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter

RVIG Lig:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter

RVIG Lig Bind:
  :asset_type: plate
  :presenter_class: Presenters::PermissivePresenter

RVIG Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  # TODO: this is the full list of templates copied from WGS/ICS and should be reduced
  :tag_layout_templates:
    - Illumina pipeline tagging
    - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
    - hWGS and RNAseq UDI tag layout v3
    - pWGS UDI tag layout v2 A
    - pWGS UDI tag layout v2 B
    - pWGS UDI tag layout v2 C
    - pWGS UDI tag layout v2 D
    - TS_pWGSA_UDI96
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSC_UDI_tag60_61_swap
    - TS_pWGSD_UDI96
    - TSRNAhWGS_UDI96
    - TS_pWGSA_UDI96v2
    - TSISC_UDI96

RVIG Lib PCR XP:
  :asset_type: plate
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :file_links:
    - name: 'Download Concentration (ng/ul) CSV for Custom Pooling'
      id: rvi_pcr_xp_concentrations_for_custom_pooling

RVIG Lib PrePool:
  :asset_type: plate
  :default_printer_type: :plate_b
  :creator_class: LabwareCreators::MultiPlatePool
  :csv_template: 'show_extended'

RVIG Hyb:
  :asset_type: plate
  :default_printer_type: :plate_b
  :creator_class: LabwareCreators::BaitedPlate
  :csv_template: 'show_extended'

RVIG Cap Lib:
  :asset_type: plate
  :default_printer_type: :plate_b

RVIG Cap Lib PCR:
  :asset_type: plate
  :default_printer_type: :plate_b

RVIG Cap Lib PCR XP:
  :asset_type: plate
  :default_printer_type: :plate_b

RVIG Cap Lib Pool:
  :asset_type: plate
  :default_printer_type: :plate_b
  :creator_class: LabwareCreators::PlateWithTemplate
  :transfer_template: 'Pool wells based on submission'
