---
# These purposes were part of the original Heron pipeline, which has been
# superseded in favour of the LTHR (tailed) workflow (heron_lthr_96).
# The associated pipeline was removed as part of
# https://github.com/sanger/limber/issues/546
LHR RT:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :default_printer_type: :plate_a
  :presenter_class: Presenters::StockPlatePresenter
LHR PCR 1:
  :asset_type: plate
LHR PCR 2:
  :asset_type: plate
LHR XP:
  :asset_type: plate
  :creator_class: LabwareCreators::MergedPlate
  :label_template: plate_xp
  :merged_plate:
    source_purposes:
      - 'LHR PCR 1'
      - 'LHR PCR 2'
    help_text: 'Here we are merging the two Primer Panel PCR plates, creating a new XP plate.'
  :file_links:
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
LHR End Prep:
  :asset_type: plate
LHR Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
    - Illumina pipeline tagging
    - 'Sanger_168tags - 10 mer tags in columns ignoring pools (first oligo: ATCACGTT)'
    - TS_pWGSA_UDI96
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSD_UDI96
    - TS_pWGSA_UDI96v2
    - TSISC_UDI96
LHR Lib Pool:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::PooledTubesBySubmission
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
LHR Lib Pool XP:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
