---
Kinnex Cherrypick:
  :asset_type: tube
  :target: SampleTube
  :type: Tube::Purpose
  :creator_class: LabwareCreators::TubesFromPlateWell
  :presenter_class: Presenters::SimpleTubePresenter
  :label_template: plate_96_2d
