# EMSeq plate purposes
---
LCMT Lysate:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: false
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
  :creator_class: LabwareCreators::Uncreatable
  :size: 96
LCMT DNA Frag:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PermissivePresenter
  :size: 96
LCMT DNA End Prep:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PermissivePresenter
  :size: 96
LCMT DNA Adp Lig:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PermissiveSubmissionPlatePresenter
  :submission_options:
    WGS Branch - Automated Submission:
      template_name: 'Limber-Htp - LCM Triomics WGS'
      allowed_extra_barcodes: false
      # We don't really need request options, but the Sequencescape API expects to
      # receive an object and won't accept an empty one, so we pass it a key it
      # it won't use and this stops it complaining about a "blank" object.
      request_options:
        # TODO: replace with the correct request options
        library_type: 'LCM Triomics WGS'
        fragment_size_required_from: '200'
        fragment_size_required_to: '800'
  :size: 96

# EM Branch
LCMT EM TET2 Ox:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PermissivePresenter
  :size: 96
LCMT EM TET2 Stop:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :size: 96
LCMT EM NaOH Denat:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :size: 96
LCMT EM APOBEC Deam:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :size: 96
LCMT EM Lib PCR:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
    - TS_pWGSA_UDI96v2
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSC_UDI_tag60_61_swap
    - TS_pWGSD_UDI96
    - TSISC_UDI96
    - TSRNAhWGS_UDI96
  :size: 96
LCMT EM PCR XP:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :file_links:
    - name: Download Concentration (nM) CSV
      id: concentrations_nm
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
  :size: 96
# Change all 'pool' refs to 'pool XP' (libraries are clean-up prior to
# pooling so the flow is directly from PCR XP to Pool XP).
LCMT EM Pool XP:
  :asset_type: tube
  :target: StockMultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::CustomPooledTubes
  :presenter_class: Presenters::SimpleTubePresenter
  :default_printer_type: :tube
LCMT EM Pool XP Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::InitialStockTubePurpose
  :creator_class: LabwareCreators::TubeFromTube
  :presenter_class: Presenters::FinalTubePresenter
  :default_printer_type: :tube

# WGS branch
LCMT DNA Lib PCR:
  :asset_type: plate
  :stock_plate: false
  :cherrypickable_target: false
  :input_plate: false
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
    - TS_pWGSA_UDI96v2
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSC_UDI_tag60_61_swap
    - TS_pWGSD_UDI96
    - TSISC_UDI96
    - TSRNAhWGS_UDI96
  :size: 96
