# A plate provided as ready-made libraries.
# These used to be imported as Stock Plates and then 'fake cherrypicked' onto 'LB Lib PCR XP', which were allowed down the multiplexing pipelines.
# Now, they can be imported and submitted as this more accurate plate purpose.
Library Stock Plate:
  :asset_type: plate
  :stock_plate: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
