# This configuration file is for the plate and tube purposes required for the
# high throughput scRNA Core cDNA Prep pipeline
---
###
# scRNA core thawing, donor pooling & cDNA prep
###
# Plate representing tube rack received from BioResource.
# In reality, the rack contains LRC Blood Seq & Spare tubes.
# Cryostor is the name of the buffer used to freeze the PBMCs.
LRC PBMC Cryostor:
  :asset_type: plate
  :size: 96
  :stock_plate: false
  :input_plate: false
  :creator_class:
    name: LabwareCreators::MultiStampTubesUsingTubeRackScan
    args:
      expected_request_type_keys:
        - 'limber_scrna_core_cdna_prep_v2'
      expected_tube_purpose_names:
        - 'LRC Bank Seq'
        - 'LRC Bank Spare'
      filename_for_tube_rack_scan: 'scrna_cryostor_tube_rack_scan.csv'
# Plate containing defrosted PBMCs in PBS buffer.
LRC PBMC Defrost PBS:
  :asset_type: plate
  :label_template: plate_cellaca_qc # creates QC1 up to QC4 barcodes
  :file_links:
    - name: 'Download Cellaca Input QC1'
      id: cellaca_input_file
      params:
        page: 0
    - name: 'Download Cellaca Input QC2'
      id: cellaca_input_file
      params:
        page: 1
    - name: 'Download Cellaca Input QC3'
      id: cellaca_input_file
      params:
        page: 2
    - name: 'Download Cellaca Input QC4'
      id: cellaca_input_file
      params:
        page: 3
  :qc_thresholds:
    viability:
      units: '%'
      default_threshold: 50
    live_cell_count:
      name: Cell count
      units: 'cells/ml'
      default_threshold: 400000
      decimal_places: 0
  :stock_plate: false
  :input_plate: false
# Plate containing pooled PBMCs from different donors.
# This plate has come from the LRC PBMC Defrost PBS plate, in SeqOps.
LRC PBMC Pools:
  :asset_type: plate
  :creator_class:
    name: LabwareCreators::DonorPoolingPlate
    args:
      # If the the lookup table in pooling configuration does not specify the
      # number of pools for a given number of samples, this value will be used.
      default_number_of_pools: 16
      # The maximum number of source plates that can be used to create the pool.
      # This is also used for bed verification of the source plates.
      max_number_of_source_plates: 2
      # The name of the pooling configuration to use. This configuration
      # contains the lookup table mapping the number of samples to the number
      # of pools. The pooling configurations are stored in the config/poolings/
      # directory. The top level key in the configuration file is the name of the
      # pooling configuration. A copy of cardinal pooling is used until a new
      # configuration is provided.
      pooling: interim_scrna_core_donor_pooling
  :stock_plate: false
  :input_plate: false
  :file_links:
    - name: 'Download Hamilton LRC PBMC Defrost PBS to LRC PBMC Pools CSV'
      id: hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools
# Plate containing pooled PBMCs from different donors.
# This plate has come from faculty and is entering the SeqOps pipeline for the first time here.
LRC PBMC Pools Input:
  :asset_type: plate
  # stock_plate has to be true so that it appears in the 'Purpose' list when generating a sample manifest in Sequencescape
  :stock_plate: true
  # input_plate has to be true so that the statechanger shows the plate as passed in the initial presenter
  :input_plate: true
  :cherrypickable_target: true
  # display as a stock plate in the UI
  :presenter_class: Presenters::StockPlatePresenter
  # will not be creatable in Limber
  :creator_class: LabwareCreators::Uncreatable
  :size: 96
# 10X Chromium 16-well chip
LRC HT 5p Chip:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
# GEMs plate, containing wells from the above in duplicate.
LRC HT 5p GEMs:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
# Plate containing cDNA (converted from RNA), straight stamp from above.
LRC HT 5p cDNA PCR:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
# Plate containing cleaned up cDNA, duplicate wells consolidated back together.
LRC HT 5p cDNA PCR XP:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
# TODO: there are more steps in the pipeline before this cherrypick plate.
LRC HT 5p Cherrypick:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  :cherrypickable_target: true
# NB. the min and max amounts for the bins are the total amount of cDNA in the well i.e.
# QC concentration * (source_volume + diluent_volume)
# TODO: R&D to confirm the ranges for each PRC cycle
LRC HT 5p cDNA Dil:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  :presenter_class: Presenters::ConcentrationBinnedPlatePresenter
  :creator_class: LabwareCreators::ConcentrationBinnedSingleCellDilPlate
  :dilutions:
    :source_volume: 20
    :diluent_volume: 0
    :bins:
      - max: 5.0
        pcr_cycles: 16
        colour: 1
      - min: 5.0
        max: 15.0
        pcr_cycles: 15
        colour: 2
      - min: 15.0
        max: 25.0
        pcr_cycles: 14
        colour: 3
      - min: 25.0
        max: 75.0
        pcr_cycles: 13
        colour: 4
      - min: 75.0
        max: 150
        pcr_cycles: 12
        colour: 5
      - min: 150.0
        max: 300.0
        pcr_cycles: 11
        colour: 6
      - min: 300.0
        max: 500.0
        pcr_cycles: 10
        colour: 7
      - min: 500.0
        max: 750.0
        pcr_cycles: 9
        colour: 8
      - min: 750.0
        max: 1000.0
        pcr_cycles: 8
        colour: 9
      - min: 1000.0
        max: 1250.0
        pcr_cycles: 7
        colour: 10
      - min: 1250.0
        max: 1500.0
        pcr_cycles: 6
        colour: 11
      - min: 1500.0
        pcr_cycles: 5
        colour: 12
  :file_links:
    - name: 'Download Hamilton LRC HT 5p Cherrypick to LRC HT 5p cDNA Dil CSV'
      id: hamilton_lrc_ht_5p_cherrypick_to_lrc_ht_5p_cdna_dil
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
