# This configuration file is for the plate and tube purposes required for the
# high throughput scRNA Core Cell Extraction pipeline
---
###
# scRNA Core Cell Extraction Arraying
###
# Donor Vacutainer tubes
LRC Blood Vac:
  :asset_type: tube
  :stock_plate: false
  :input_plate: false
  :target: SampleTube
  :type: Tube::Purpose
  :presenter_class: Presenters::StockTubePresenter
  :creator_class: LabwareCreators::Uncreatable
  :default_printer_type: :tube
# Manually aliquoted intermediate tube
LRC Blood Aliquot:
  :asset_type: tube
  :stock_plate: false
  :input_plate: false
  :target: SampleTube
  :type: Tube::Purpose
  :presenter_class: Presenters::SimpleTubePresenter
  :creator_class: LabwareCreators::TubeFromTube
  :label_template: plate_96_2d # uses a plate printer because it's a 'falcon tube'
  :alternative_workline_identifier: LRC Blood Vac
###
# scRNA Core Cell Extraction Blood Pipeline
###
# Input plate for Hamilton PBMC isolation protocol
# LRC Blood Vac tubes are also arrayed into LRC Blood Bank plates (DPL-073)
LRC Blood Bank:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  :creator_class:
    name: LabwareCreators::MultiStampTubes
    params:
      allow_tube_duplicates: yes
      require_tube_passed: yes
      acceptable_purposes: ['LRC Blood Aliquot']
  :submission_options:
    scRNA core cell extraction:
      template_name: 'Limber - scRNA Core Cell Extraction'
      request_options:
        fragment_size_required_from: '200'
        fragment_size_required_to: '800'
      allowed_extra_barcodes: false
      autodetect_studies: true
      autodetect_projects: false
  :file_links:
    - name: 'Download Scanned Tube Layout for LRC Blood Bank Plate'
      id: scrna_core_cell_extraction_sample_arraying_tube_layout
# LRC Blood Bank plates are stamped into LRC PBMC Bank plates
# Output plate from Hamilton PBMC isolation protocol / input plate for the cell counting and cell banking protocols
LRC PBMC Bank:
  :asset_type: plate
  # Labware creator for pooling isolations by sample before cell counting
  :creator_class:
    name: LabwareCreators::PooledWellsBySampleInGroups
    args:
      # number of source wells to pool into a single destination well by sample from LRC Bank to LRC PBMC Bank
      # e.g. 6 copies of sample in 6 wells, '2' in the config, pool to make 3 child wells
      number_of_source_wells: 2
  :label_template: plate_quad_qc # creates QC4 barcodes
  :file_links:
    - name: 'Download Hamilton LRC Blood Bank plate to LRC PBMC Bank plate CSV'
      id: hamilton_lrc_blood_bank_to_lrc_pbmc_bank
    - name: 'Download PBMC Bank Tubes Content Report'
      id: pbmc_bank_tubes_content_report
      states: [passed, qc_complete]
    - name: 'Download Cellaca FIRST Count CSV'
      id: hamilton_lrc_pbmc_bank_to_cellaca_first_count
    - name: 'Download Cellaca SECOND Count CSV'
      id: hamilton_lrc_pbmc_bank_to_cellaca_second_count
  :qc_thresholds:
    viability:
      units: '%'
      default_threshold: 85
    total_cell_count:
      name: Total cell count
      units: 'cells/ml'
      default_threshold: 650000
      decimal_places: 0
# Tube rack for storing LRC Bank Seq tubes
LRC TR Bank Seq:
  :asset_type: tube_rack
  :target: TubeRack
  :size: 96
  :type: TubeRack::Purpose
  :creator_class:
    name: LabwareCreators::PlateSplitToTubeRacks
    args: &fluidx_tube_creation_config
      child_seq_tube_purpose_name: LRC Bank Seq
      child_seq_tube_name_prefix: SEQ
      child_seq_tube_rack_purpose_name: LRC TR Bank Seq
      child_spare_tube_purpose_name: LRC Bank Spare
      child_spare_tube_name_prefix: SPR
      child_spare_tube_rack_purpose_name: LRC TR Bank Spare
      ancestor_stock_tube_purpose_name: LRC Blood Vac
  :presenter_class: Presenters::TubeRackPresenter
  # This needs to be the AutomaticTubeRackStateChanger.
  # But, the work-completion for the AutomaticTubeRackStateChanger is not yet
  # fixed for TubeRacks (this needs to be done in Sequencescape). So, for now,
  # we are using the TubeRackStateChanger for Manual Transfers.
  # See: https://github.com/sanger/limber/issues/2074
  :state_changer_class: StateChangers::AutomaticTubeRackStateChanger
  :work_completion_request_type: 'limber_scrna_core_cell_extraction'
  :file_links:
    - name: Download Racked Tube Concentrations (ng/ul) CSV
      id: tube_rack_concentrations_ngul
    - name: Download Racked Tube Concentrations (nM) CSV
      id: tube_rack_concentrations_nm
    - name: 'Download Hamilton LRC PBMC Bank plate to LRC Bank Seq and Spare tubes CSV'
      id: hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare
# Tube rack for storing LRC Bank Spare tubes
LRC TR Bank Spare:
  :asset_type: tube_rack
  :target: TubeRack
  :size: 96
  :type: TubeRack::Purpose
  :creator_class:
    name: LabwareCreators::PlateSplitToTubeRacks
    args: *fluidx_tube_creation_config
  :presenter_class: Presenters::TubeRackPresenter
  # This needs to be the AutomaticTubeRackStateChanger.
  # But, the work-completion for the AutomaticTubeRackStateChanger is not yet
  # fixed for TubeRacks (this needs to be done in Sequencescape). So, for now,
  # we are using the TubeRackStateChanger for Manual Transfers.
  # See: https://github.com/sanger/limber/issues/2074
  :state_changer_class: StateChangers::AutomaticTubeRackStateChanger
  :work_completion_request_type: 'limber_scrna_core_cell_extraction'
  :file_links:
    - name: Download Tube Rack Concentrations (ng/ul) CSV
      id: tube_rack_concentrations_ngul
    - name: Download Racked Tube Concentrations (nM) CSV
      id: tube_rack_concentrations_nm
    - name: 'Download Hamilton LRC PBMC Bank plate to LRC Bank Seq and Spare tubes CSV'
      id: hamilton_lrc_pbmc_bank_to_lrc_bank_seq_and_spare
# FluidX tube for freezing and output of cell banking protocol
LRC Bank Seq:
  :asset_type: tube
  :target: SampleTube
  :type: Tube::Purpose
  :creator_class: LabwareCreators::Uncreatable
  :presenter_class: Presenters::SimpleTubePresenter
# FluidX tube for freezing and output of cell banking protocol
LRC Bank Spare:
  :asset_type: tube
  :target: SampleTube
  :type: Tube::Purpose
  :creator_class: LabwareCreators::Uncreatable
  :presenter_class: Presenters::SimpleTubePresenter
# FluidX tube frozen input from faculty tube, created by manifest
LRC Bank Input:
  :asset_type: tube
  :target: SampleTube
  :type: Tube::Purpose
  :creator_class: LabwareCreators::Uncreatable
  :presenter_class: Presenters::StockTubePresenter
