# This configuration file is for the plate and tube purposes required for the
# high throughput scRNA Core cDNA Prep pipeline
---
###
# scRNA core thawing, donor pooling & cDNA prep
###
# Plate representing tube rack received from BioResource.
# In reality, the rack contains LRC Blood Seq & Spare tubes.
# Cryostor is the name of the buffer used to freeze the PBMCs.
LRC PBMC Cryostor:
  :asset_type: plate
  :size: 96
  :stock_plate: false
  :input_plate: false
  :creator_class:
    name: LabwareCreators::MultiStampTubesUsingTubeRackScan
    args:
      expected_request_type_keys:
        - 'limber_scrna_core_cdna_prep_v2'
      expected_tube_purpose_names:
        - 'LRC Bank Seq'
        - 'LRC Bank Spare'
      filename_for_tube_rack_scan: 'scrna_cryostor_tube_rack_scan.csv'
# Plate containing defrosted PBMCs in PBS buffer.
LRC PBMC Defrost PBS:
  :asset_type: plate
  :label_template: plate_quad_qc # creates QC4 barcodes
  :file_links:
    - name: 'Download Cellaca CSV'
      id: hamilton_lrc_pbmc_defrost_pbs_to_cellaca
    - name: 'Download Cellaca Input QC1'
      id: cellaca_input_file
      params:
        page: 0
    - name: 'Download Cellaca Input QC2'
      id: cellaca_input_file
      params:
        page: 1
    - name: 'Download Cellaca Input QC3'
      id: cellaca_input_file
      params:
        page: 2
    - name: 'Download Cellaca Input QC4'
      id: cellaca_input_file
      params:
        page: 3
  :qc_thresholds:
    viability:
      units: '%'
      default_threshold: 50
    live_cell_count:
      name: Cell count
      units: 'cells/ml'
      default_threshold: 400000
      decimal_places: 0
  :stock_plate: false
  :input_plate: false
# Plate containing pooled PBMCs from different donors.
# This plate has come from the LRC PBMC Defrost PBS plate, in SeqOps.
LRC PBMC Pools:
  :asset_type: plate
  :presenter_class:
    name: Presenters::DonorPoolingPlatePresenter
    args:
      # The default number of cells to calculate the required volumes.
      default_required_number_of_cells: 5000
      # poly_metadatum key for study specific required number of cells.
      study_required_number_of_cells_key: scrna_core_pbmc_donor_pooling_required_number_of_cells
  :creator_class:
    name: LabwareCreators::DonorPoolingPlate
    args:
      # If the the lookup table in pooling configuration does not specify the
      # number of pools for a given number of samples, this value will be used.
      default_number_of_pools: 16
      # The maximum number of source plates that can be used to create the pool.
      # This is also used for bed verification of the source plates.
      max_number_of_source_plates: 2
      # The name of the pooling configuration to use. This configuration
      # contains the lookup table mapping the number of samples to the number
      # of pools. The pooling configurations are stored in the config/poolings/
      # directory. The top level key in the configuration file is the name of the
      # pooling configuration. A copy of cardinal pooling is used until a new
      # configuration is provided.
      pooling: interim_scrna_core_donor_pooling
  :stock_plate: false
  :input_plate: false
  :file_links:
    - name: 'Download Hamilton LRC PBMC Defrost PBS to LRC PBMC Pools CSV'
      id: hamilton_lrc_pbmc_defrost_pbs_to_lrc_pbmc_pools
# Plate containing pooled PBMCs from different donors.
# This plate has come from faculty and is entering the SeqOps pipeline for the first time here.
LRC PBMC Pools Input:
  :asset_type: plate
  # stock_plate has to be true so that it appears in the 'Purpose' list when generating a sample manifest in Sequencescape
  :stock_plate: true
  # input_plate has to be true so that the statechanger shows the plate as passed in the initial presenter
  :input_plate: true
  :cherrypickable_target: true
  # display as a stock plate in the UI
  :presenter_class: Presenters::StockPlatePresenter
  # will not be creatable in Limber
  :creator_class: LabwareCreators::Uncreatable
  :size: 96
# 10X Chromium 8-well chip
LRC GEM-X 5p Chip:
  :asset_type: plate
  # NB. The Shape8x1 shape (for 8-well Chromium Chip) configured here differs
  # from the Shape4x1 shape (for 16-well Chromium Chip). Specifically, their
  # horizontal to vertical ratios are 8:1 and 4:1, respectively.
  :asset_shape: Shape8x1
  :size: 8
  :stock_plate: false
  :input_plate: false
  :creator_class: LabwareCreators::StampedPlateReorderingColumnsToRows
  # ChromiumChipPresenter has been added to disable the incompatible pooling tab.
  :presenter_class: Presenters::ChromiumChipPresenter
# GEMs plate, containing wells from the above in duplicate.
LRC GEM-X 5p GEMs:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  :creator_class: LabwareCreators::StampedPlateCompressed
# Plate containing cDNA (converted from RNA), straight stamp from above.
LRC GEM-X 5p cDNA PCR:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
# Plate containing cleaned up cDNA, duplicate wells consolidated back together.
# TODO: check whether the stock and or input plate flags are correct to allow an aggregation
# submission to be created on this plate
LRC GEM-X 5p cDNA PCR XP:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  # close off the submission when the plate is created
  :state_changer_class: StateChangers::AutomaticPlateStateChanger
  :work_completion_request_type: 'limber_scrna_core_cdna_prep_input'
# faculty input plate (alternate to LRC GEM-X 5p cDNA PCR XP intermediate plate)
LRC GEM-X 5p cDNA Input:
  :asset_type: plate
  :stock_plate: true
  :input_plate: true
  # display as a stock plate in the UI
  :presenter_class: Presenters::StockPlatePresenter
  # will not be creatable in Limber (created by manifest in Sequencescape)
  :creator_class: LabwareCreators::Uncreatable
# There will be a manual submission on a sub-selection of samples in the LRC GEM-X 5p cDNA PCR XP and
# LRC GEM-X 5p cDNA Input plates for aggregation into a single LRC GEM-X 5p Cherrypick plate. Multiple plates
# could be aggregated into a single cherrypick plate.
# e.g. if single samples are selected from each plate then up to 10 aggregate plates could be made which are
# then combined into a single cherrypick plate.
LRC GEM-X 5p Aggregate:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  :creator_class: LabwareCreators::TenStamp
  :file_links: []
# NB. QC concentrations need to be uploaded via QuantHub for the Cherrypick plate in order for the binning
# calculations in the GEX Dil plate step to work.
# TODO: there will be a submission on this plate for library prep
# TODO: not clear what the stock and input flags should be for this to work
LRC GEM-X 5p Cherrypick:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  :cherrypickable_target: true
  :creator_class: LabwareCreators::TenStamp
  :state_changer_class: StateChangers::AutomaticPlateStateChanger
  :work_completion_request_type: 'limber_scrna_core_chromium_gem_x_5p_aggregation'
  :file_links:
    - name: 'Download Hamilton Aggregate Cherrypick CSV'
      id: 'hamilton_aggregate_cherrypick'
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
# NB. For the following binning step the min and max amounts for the bins are the total amount of cDNA
# in the well i.e. QC concentration * (source_volume + diluent_volume)
# Here we are using a fixed source volume and there is no dilution (diluent_volume = 0)
# TODO: R&D to confirm the number of PCR cycles for each range
LRC GEM-X 5p GEX Dil:
  :asset_type: plate
  :stock_plate: false
  :input_plate: false
  :presenter_class: Presenters::ConcentrationBinnedPlatePresenter
  :creator_class: LabwareCreators::ConcentrationBinnedPlate
  :dilutions:
    :source_volume: 10
    :diluent_volume: 0
    :bins:
      - max: 25.0
        pcr_cycles: 15
        colour: 1
      - min: 25.0
        max: 150.0
        pcr_cycles: 13
        colour: 2
      - min: 150.0
        max: 500.0
        pcr_cycles: 11
        colour: 3
      - min: 500.0
        max: 1000.0
        pcr_cycles: 9
        colour: 4
      - min: 1000.0
        max: 1500.0
        pcr_cycles: 7
        colour: 5
      - min: 1500.0
        pcr_cycles: 5
        colour: 12
  :file_links:
    - name: 'Download Hamilton LRC GEM-X 5p Cherrypick to LRC GEM-X 5p GEX Dil CSV'
      id: hamilton_lrc_gem_x_5p_cherrypick_to_lrc_gem_x_5p_gex_dil
    - name: Download Concentration (ng/ul) CSV
      id: concentrations_ngul
# TODO: there will be further library prep steps after this plate
