# This configuration file is for the plate and tube purposes required for the
# high throughput Targeted NanoSeq pipeline
---
LTN Stock:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: false
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
LTN Cherrypick:
  :asset_type: plate
  :stock_plate: true
  :cherrypickable_target: true
  :input_plate: true
  :presenter_class: Presenters::StockPlatePresenter
LTN Shear:
  :asset_type: plate
LTN Post Shear:
  :asset_type: plate
LTN Stock XP:
  :asset_type: plate
LTN AL Lib:
  :asset_type: plate
  :label_template: plate_ltn_al_lib
  :state_changer_class: StateChangers::AutomaticPlateStateChanger
  :work_completion_request_type: 'limber_targeted_nanoseq'
  :file_links:
    - name: 'Download Hamilton AL Lib to QC1 CSV'
      id: 'hamilton_ltn_al_lib_to_qc1'
    - name: 'Download Concentration (nM) CSV for Customer'
      id: 'targeted_nanoseq_al_lib_concentrations_for_customer'
LTN AL Lib Dil:
  :asset_type: plate
  :presenter_class: Presenters::PcrCyclesBinnedPlateUsingRequestMetadataPresenter
  :creator_class: LabwareCreators::PcrCyclesBinnedPlateForTNanoSeq
  :csv_file_upload:
    :input_amount_desired_min: 0.0
    :input_amount_desired_max: 10000.0
    :sample_volume_min: 0.2
    :sample_volume_max: 50.0
    :diluent_volume_min: 0.0
    :diluent_volume_max: 50.0
    :pcr_cycles_min: 1
    :pcr_cycles_max: 20
  :expected_binning_request_type: 'limber_targeted_nanoseq_isc_prep'
  :file_links:
    - name: 'Download Hamilton AL Lib to Dilution CSV'
      id: 'hamilton_ltn_al_lib_to_ltn_al_lib_dil'
LTN Lib PCR:
  :asset_type: plate
  :presenter_class: Presenters::PcrPresenter
  :creator_class: LabwareCreators::TaggedPlate
  :tag_layout_templates:
    - TS_pWGSA_UDI96
    - TS_pWGSA_UDI96v2
    - TS_pWGSB_UDI96
    - TS_pWGSC_UDI96
    - TS_pWGSC_UDI_tag60_61_swap
    - TS_pWGSD_UDI96
    - TS_RNAhWGS_UDI_96
LTN Lib PCR XP:
  :asset_type: plate
  :default_printer_type: :plate_b
  :label_template: plate_xp
  :state_changer_class: StateChangers::AutomaticPlateStateChanger
  :work_completion_request_type: 'limber_targeted_nanoseq_isc_prep'
  :file_links:
    - name: 'Download Merged File CSV'
      id: 'targeted_nanoseq_pcr_xp_merged_file'
