---
# I'm not sure how long this will stay around, as I *think* we'll probably want
# to handle tube racks slightly differently. But popping this here while I
# investigate
TR Stock 96:
  :asset_type: tube_rack
  :size: 96
TR Stock 48:
  :asset_type: tube_rack
  :size: 48
Heron Lysed Tube Rack:
  :asset_type: tube_rack
  :size: 96
