---
# Only used when there are more than 10 source plates (the robot has 10 source
# slots). Up to 10 of these are then aggregated into ULTP DNA Norm.
ULTP Aggregate:
  :asset_type: plate
  :creator_class:
    name: LabwareCreators::TenStamp
    args:
      acceptable_purposes:
        - LB Lib PCR-XP
        - LTN Lib PCR XP
        - RVI Lib PCR XP
        - RVIG Lib PCR XP
        - LBB Lib PCR-XP
        - LBB Lib PCR-XP Norm
        - Library Stock Plate
      request_type_keys:
        - limber_ultima_ltp_aggregation
# Aggregates the submitted wells of Illumina library plates, or ULTP Aggregate
# plates. The conversion submission is made on this plate.
# Normalisation is done outside LIMS for the MVP, so TenStamp records one
# volume for all wells.
ULTP DNA Norm:
  :asset_type: plate
  :creator_class:
    name: LabwareCreators::TenStamp
    args:
      acceptable_purposes:
        - LB Lib PCR-XP
        - LTN Lib PCR XP
        - RVI Lib PCR XP
        - RVIG Lib PCR XP
        - LBB Lib PCR-XP
        - LBB Lib PCR-XP Norm
        - Library Stock Plate
        - ULTP Aggregate
      request_type_keys:
        - limber_ultima_ltp_aggregation
        - limber_ultima_ltp_conversion
  :presenter_class: Presenters::UltimaConversionPresenter
  :tag_group_adapter_type_name_filter: 'Ultima'
  :tag_sets:
    - Ultima P1 v1
    - Ultima P1 v2
    - Ultima P2
    - Ultima P3
    - UG-RD-1916
    - UG-RD-1940
  :state_changer_class: StateChangers::AutomaticPlateStateChanger
  :work_completion_request_type: 'limber_ultima_ltp_aggregation'
ULTP PCR XP:
  :asset_type: plate
  :default_printer_type: :plate_xp2
ULTP Lib Norm:
  :asset_type: plate
ULTP Lib Pool Norm:
  :asset_type: tube
  :target: MultiplexedLibraryTube
  :type: IlluminaHtp::MxTubePurpose
  :creator_class: LabwareCreators::FinalTubeFromPlate
  :presenter_class: Presenters::FinalTubePresenter
  :default_printer_type: :ultima_balanced_norm_tube
