# WIP: Initial step of pipeline only
---
Bespoke Chromium TCR:
  filters:
    request_type_key: limber_chromium_bespoke
    library_type: Chromium single cell TCR
  library_pass: LBC TCR Post PCR
  relationships:
    LBC Cherrypick: LBC TCR Dil 1
    LBC TCR Dil 1: LBC TCR Enrich1 2XSPRI
    LBC TCR Enrich1 2XSPRI: LBC TCR Enrich2 2XSPRI
    LBC TCR Enrich2 2XSPRI: LBC TCR Dil 2
    LBC TCR Dil 2: LBC TCR Post Lig 1XSPRI
    LBC TCR Post Lig 1XSPRI: LBC TCR Post PCR
Bespoke Chromium TCR MX:
  filters:
    request_type_key:
      - limber_multiplexing
  relationships:
    LBC TCR Post PCR: LBC TCR LibPS
    LBC TCR LibPS: LB Lib Pool Norm
