Bespoke PCR MX HiC:
  filters:
    request_type_key: limber_multiplexing_hic
  relationships:
    LBB Lib PCR-XP: LBB Lib PCR-XP Norm
    LBB Lib PCR-XP Norm: LBB Lib Pool Stock
    LBB Lib Pool Stock: LB Lib Pool Norm
