---
# This is the pipeline configuration for EMSeq
EMSeq DNA Prep:
  filters:
    request_type_key: limber_emseq_dna_prep
  relationships:
    LCMT Lysate: LCMT DNA Adp Lig

EMSeq WGS Transition:
  relationships:
    LCMT DNA Adp Lig: LCMT DNA Lib PCR

EMSeq EM Transition:
  relationships:
    LCMT DNA Adp Lig: LCMT EM TET2 Ox

EMSeq WGS Library Prep:
  filter:
    request_type_key: limber_emseq_wgs_library_prep
    library_type: EMSeq WGS
  # TODO: Add relationships for EMSeq WGS Library Prep
  # relationships:
  #   LCMT DNA Lib PCR: XXX

EMSeq EM Library Prep:
  filter:
    request_type_key: limber_emseq_em_library_prep
    library_type: EMSeq EM
  # TODO: Add relationships for EMSeq EM Library Prep
  # relationships:
  #   LCMT EM TET2 Ox: XXX
