---
scRNA Core Chromium GEM-X 5p BCR:
  pipeline_group: scRNA Core BCR Library Prep
  filters:
    request_type_key: limber_scrna_core_library_prep
    library_type: Chromium single cell GEM-X 5p v3 BCR
  library_pass: LRC GEM-X 5p BCR Post PCR
  relationships:
    LRC GEM-X 5p Cherrypick: LRC GEM-X 5p BCR Dil 1
    LRC GEM-X 5p BCR Dil 1: LRC GEM-X 5p BCR Enrich1 2XSPRI
    LRC GEM-X 5p BCR Enrich1 2XSPRI: LRC GEM-X 5p BCR Enrich2 2XSPRI
    LRC GEM-X 5p BCR Enrich2 2XSPRI: LRC GEM-X 5p BCR Dil 2
    LRC GEM-X 5p BCR Dil 2: LRC GEM-X 5p BCR Post Lig 1XSPRI
    LRC GEM-X 5p BCR Post Lig 1XSPRI: LRC GEM-X 5p BCR Post PCR
scRNA Core Chromium GEM-X 5p BCR Pool Norm:
  pipeline_group: scRNA Core Library Prep
  filters:
    request_type_key:
      - scrna_core_pool_norm
  relationships:
    LRC GEM-X 5p BCR Post PCR: LRC GEM-X 5p BCR LibPS
    LRC GEM-X 5p BCR LibPS: LRC GEM-X 5p BCR Pool Norm
