---
# Pipeline configuration for EMSeq
LCM Triomics EMSeq:
  pipeline_group: LCM Triomics WGS and EMSeq
  filters:
    request_type_key: limber_lcm_triomics_emseq
    library_type: LCM Triomics EMSeq
  library_pass: LCMT EM PCR XP
  relationships:
    LCMT Lysate: LCMT DNA Frag
    LCMT DNA Frag: LCMT DNA End Prep
    LCMT DNA End Prep: LCMT DNA Adp Lig
    LCMT DNA Adp Lig: LCMT EM TET2 Ox
    LCMT EM TET2 Ox: LCMT EM TET2 Stop
    LCMT EM TET2 Stop: LCMT EM NaOH Denat
    LCMT EM NaOH Denat: LCMT EM APOBEC Deam
    LCMT EM APOBEC Deam: LCMT EM Lib PCR
    LCMT EM Lib PCR: LCMT EM PCR XP

LCM Triomics EMSeq Custom Pooling:
  pipeline_group: LCM Triomics WGS and EMSeq
  filters:
    request_type_key: limber_lcm_triomics_emseq
    state: passed
  relationships:
    LCMT EM PCR XP: LCMT EM Pool XP
    LCMT EM Pool XP: LCMT EM Pool XP Norm

# Pipeline configuration for WGS
LCM Triomics WGS:
  pipeline_group: LCM Triomics WGS and EMSeq
  filters:
    request_type_key: limber_lcm_triomics_wgs
    library_type: LCM Triomics WGS
  library_pass: LCMT DNA PCR XP
  relationships:
    LCMT DNA Adp Lig: LCMT DNA Lib PCR
    LCMT DNA Lib PCR: LCMT DNA PCR XP
LCM Triomics WGS Custom Pooling:
  pipeline_group: LCM Triomics WGS and EMSeq
  filters:
    request_type_key: limber_lcm_triomics_wgs
    state: passed
  relationships:
    LCMT EM PCR XP: LCMT DNA Pool XP
    LCMT EM Pool XP: LCMT DNA Pool XP Norm
