---
WGS: # Top of the pipeline (Library Prep)
  pipeline_group: WGS
  filters:
    request_type_key:
      - limber_wgs
      - limber_rnaa
    library_type: Standard
  library_pass: LB Lib PCR-XP
  relationships:
    LB Cherrypick: LB Shear
    LB Shear: LB Post Shear
    LB Post Shear: LB End Prep
    LB End Prep: LB Lib PCR
    LB Lib PCR: LB Lib PCR-XP
WGS MX: # Bottom of the pipeline (Pooling and normalization)
  pipeline_group: WGS
  filters:
    request_type_key:
      - limber_multiplexing
  relationships:
    Library Stock Plate: LB Lib Pool #These are supplied as ready-made libraries and enter the pipeline at this point.
    LB Lib PCR-XP: LB Lib Pool
    LB Lib Pool: LB Lib Pool Norm
