---
# scRNA Core Cell Extraction pipeline
scRNA Core Cell Extraction Seq:
  pipeline_group: scRNA Core Cell Extraction
  filters:
    request_type_key: limber_scrna_core_cell_extraction
  relationships:
    LRC Blood Vac: LRC Blood Bank
    LRC Blood Bank: LRC PBMC Bank
    LRC PBMC Bank: LRC Bank Seq
scRNA Core Cell Extraction Spare:
  pipeline_group: scRNA Core Cell Extraction
  filters:
    request_type_key: limber_scrna_core_cell_extraction
  relationships:
    LRC Blood Vac: LRC Blood Bank
    LRC Blood Bank: LRC PBMC Bank
    LRC PBMC Bank: LRC Bank Spare
