---
# Stamping of deep well plates imported via Lighthouse UI to shallow well plates
Deep-Well-96 Stamping:
  pipeline_group: Deep-Well-96 Stamping
  filters:
    request_type_key: deep_well_plate_stamping
  relationships:
    LDW-96 Stock: LSW-96 Stock
