---
Heron-384 Tailed A V2: # Heron 384-well pipeline specific to PCR 1 plate
  pipeline_group: Heron-384 V2
  filters: &heron_tailed_filters
    request_type_key: limber_heron_lthr_v2
    library_type:
      - Sanger_tailed_artic_v1_384
  library_pass: LB Lib Pool Norm
  relationships:
    LTHR Cherrypick: LTHR-384 RT-Q
    LTHR-384 RT-Q: LTHR-384 PCR 1
    LTHR-384 RT: LTHR-384 PCR 1
    LTHR-384 PCR 1: LTHR-384 Lib PCR 1
    LTHR-384 Lib PCR 1: LTHR-384 Lib PCR pool
    LTHR-384 Lib PCR pool: LTHR-384 Pool XP
    LTHR-384 Pool XP: LB Lib Pool Norm
Heron-384 Tailed B V2:
  pipeline_group: Heron-384 V2
  filters: *heron_tailed_filters
  library_pass: LB Lib Pool Norm
  relationships:
    LTHR-384 RT-Q: LTHR-384 PCR 2
    LTHR-384 RT: LTHR-384 PCR 2
    LTHR-384 PCR 2: LTHR-384 Lib PCR 2
    LTHR-384 Lib PCR 2: LTHR-384 Lib PCR pool
