---
# Pipeline configuration for EMSeq
LCM Triomics EMSeq:
  pipeline_group: LCM Triomics WGS and EMSeq
  filters:
    request_type_key: limber_lcm_triomics_emseq
    library_type: LCM Triomics EMSeq
  library_pass: LCMT EM LibPCR
  relationships:
    LCMT Lysate: LCMT DNA Frag
    LCMT DNA Frag: LCMT DNA End Prep
    LCMT DNA End Prep: LCMT DNA Adp Lig
    LCMT DNA Adp Lig: LCMT EM TET2 Ox
    LCMT EM TET2 Ox: LCMT EM TET2 Stop
    LCMT EM TET2 Stop: LCMT EM NaOH Denat
    LCMT EM NaOH Denat: LCMT EM APOBEC Deam
    LCMT EM APOBEC Deam: LCMT EM LibPCR

LCM Triomics EMSeq Pooling:
  pipeline_group: LCM Triomics WGS and EMSeq
  filters:
    request_type_key: limber_lcm_triomics_emseq
    state: passed
  relationships:
    LCMT EM LibPCR: LCMT EM PCRXP
    LCMT EM PCRXP: LCMT EM Pool XP
    LCMT EM Pool XP: LCMT EM Pool XP Norm
