---
Targeted NanoSeq:
  pipeline_group: Targeted NanoSeq
  filters: &targeted_nanoseq_filters
    request_type_key: limber_targeted_nanoseq
    library_type:
      - Targeted Nanoseq
  library_pass: LTN AL Lib
  relationships:
    LTN Stock: LTN Stock XP
    LTN Cherrypick: LTN Shear
    LTN Shear: LTN Post Shear
    LTN Post Shear: LTN Stock XP
    LTN Stock XP: LTN AL Lib
    LTN AL Lib: LTN AL Lib Dil
# Targeted NanoSeq Dilution and Cleanup part of pipeline
# Split with new submission to allow a partial selection
# of samples to go forward.
Targeted NanoSeq Dilution and Cleanup:
  filters: &targeted_nanoseq_dilution_and_cleanup_filters
    request_type_key: limber_targeted_nanoseq_dilution_and_cleanup
  library_pass: LTN Lib PCR XP
  relationships:
    LTN AL Lib Dil: LTN Lib PCR
    LTN Lib PCR: LTN Lib PCR XP
    LTN Lib PCR XP: LTN Custom Pool
    LTN Custom Pool: LTN Custom Pool Norm
Targeted NanoSeq with ISC Dilution and Cleanup:
  pipeline_group: Targeted NanoSeq with ISC
  filters: *targeted_nanoseq_dilution_and_cleanup_filters
  library_pass: LTN Lib PCR XP
  relationships:
    LTN AL Lib Dil: LTN Lib PCR
    LTN Lib PCR: LTN Lib PCR XP
    LTN Lib PCR XP: LB Lib PCR-XP
