---
# Initial transfer from tube to plate, as entry for one or other of below pipelines. Happens without submissions / requests.
Cardinal Entry A:
  relationships:
    LCA Blood Vac: LCA Blood Array
Cardinal Entry B:
  relationships:
    LCA Blood Vac: LCA Blood Bank
# Cardinal library preparation pipeline
Cardinal:
  filters:
    request_type_key: limber_cardinal
    library_type: Cardinal
  library_pass: LCA Connect PCRXP
  relationships:
    LCA Blood Array: LCA PBMC
    LCA PBMC: LCA PBMC Pools
    LCA PBMC Pools: LCA 10X cDNA
    LCA 10X cDNA: LCA Connect PCRXP
    LCA Connect PCRXP: LCA Custom Pool
    LCA Custom Pool: LCA Custom Pool Norm
# Cardinal cell banking pipeline
Cardinal Banking:
  filters:
    request_type_key: limber_cardinal_banking
    library_type: Cardinal Banking
  relationships:
    LCA Blood Bank: LCA PBMC Bank
    # TODO: DPL-074 what happens next here? Is the plate handed over to samples extraction for transfer into tube rack?
