---
Targeted NanoSeq Library Prep:
  pipeline_group: Targeted NanoSeq Library Prep
  filters: &targeted_nanoseq_filters
    request_type_key: limber_targeted_nanoseq
    library_type:
      - Targeted Nanoseq
  library_pass: LTN Lib PCR XP
  relationships:
    # Allow bypassing of sheating to get to LTN Stock XP
    LTN Stock: LTN Stock XP
    # Alternate route begins with a Cherrypick plate and includes shearing
    LTN Cherrypick: LTN Shear
    LTN Shear: LTN Post Shear
    LTN Post Shear: LTN Stock XP
    # Both routes end with creation of the LTN AL Lib plate
    LTN Stock XP: LTN AL Lib
    # End of library prep at LTN AL Lib plate
Targeted NanoSeq ISC Prep:
  pipeline_group: Targeted NanoSeq ISC Prep
  # TODO: check if we need library type here as Customer request
  filters: *targeted_nanoseq_filters
  relationships:
    LTN AL Lib: LTN AL Lib Dil
    LTN AL Lib Dil: LTN Lib PCR
    LTN Lib PCR: LTN Lib PCR XP
# TODO: do we want to define this separate to the other re-ISC pipeline configs?
Targeted NanoSeq ISC:
  pipeline_group: Targeted NanoSeq ISC
  filters:
    request_type_key:
      - limber_reisc
    library_type:
      # TODO: confirming which library types are needed here
      - Targeted NanoSeq Pulldown Twist
      - Targeted NanoSeq Pulldown Agilent
  library_pass:
    - LB Cap Lib PCR-XP
  relationships:
    LTN Lib PCR XP: LB Lib PrePool
    # TODO: do we need rest here to LB Cap Lib PCR-XP?
