---
# This is the pipeline configuration for EMSeq
LCM Triomics DNA Prep:
  filters:
    request_type_key: limber_lcm_triomics_dna_prep
  relationships:
    LCMT Lysate: LCMT DNA Adp Lig

EMSeq WGS Transition:
  relationships:
    LCMT DNA Adp Lig: LCMT DNA Lib PCR

EMSeq EM Transition:
  relationships:
    LCMT DNA Adp Lig: LCMT EM TET2 Ox

EMSeq WGS Library Prep:
  filter:
    request_type_key: limber_lcm_triomics_dna_wgs_library_prep
    library_type: LCM Triomics DNA WGS
  # TODO: Add relationships for EMSeq WGS Library Prep
  # relationships:
  #   LCMT DNA Lib PCR: XXX

EMSeq EM Library Prep:
  filter:
    request_type_key: limber_lcm_triomics_dna_emseq_library_prep
    library_type: LCM Triomics DNA EMSeq
  # TODO: Add relationships for EMSeq EM Library Prep
  # relationships:
  #   LCMT EM TET2 Ox: XXX
