---
# Thawing PBMCs and pooling samples from different donors together
scRNA Core Donor Pooling:
  pipeline_group: scRNA Core cDNA Prep
  filters:
    request_type_key:
      - limber_scrna_core_donor_pooling
  relationships:
    LRC Bank Seq: LRC PBMC Cryostor
    LRC Bank Spare: LRC PBMC Cryostor
    LRC PBMC Cryostor: LRC PBMC Defrost PBS
    LRC PBMC Defrost PBS: LRC PBMC Pools
# GEM generation and cDNA Prep
scRNA Core cDNA Prep:
  pipeline_group: scRNA Core cDNA Prep
  filters:
    request_type_key:
      - limber_scrna_core_cdna_prep
    library_type:
      - Chromium single cell 5 prime HT v2
  relationships:
    LRC PBMC Pools: LRC HT 5p Chip
    LRC PBMC Pools Input: LRC HT 5p Chip
    LRC HT 5p Chip: LRC HT 5p GEMs
    LRC HT 5p GEMs: LRC HT 5p cDNA PCR
    LRC HT 5p cDNA PCR: LRC HT 5p cDNA PCR XP
