---
Targeted NanoSeq Library Prep:
  pipeline_group: Targeted NanoSeq Library Prep
  filters: &targeted_nanoseq_filters
    request_type: limber_targeted_nanoseq
    library_type:
      - Targeted Nanoseq
  library_pass: LTN AL Lib
  relationships:
    # Allow bypassing of sheating to get to LTN Stock XP
    LTN Stock: LTN Stock XP
    # Alternate route begins with a Cherrypick plate and includes shearing
    LTN Cherrypick: LTN Shear
    LTN Shear: LTN Post Shear
    LTN Post Shear: LTN Stock XP
    # Both routes end with creation of the LTN AL Lib plate
    LTN Stock XP: LTN AL Lib
    # End of library prep at LTN AL Lib plate - can submit LTN AL Lib plates for ISC Prep
Targeted NanoSeq ISC Prep:
  pipeline_group: Targeted NanoSeq ISC Prep
  filters:
    request_type: limber_targeted_nanoseq_isc_prep
  relationships:
    LTN AL Lib: LTN AL Lib Dil
    LTN AL Lib Dil: LTN Lib PCR
    LTN Lib PCR: LTN Lib PCR XP
    # End of ISC prep at LTN Lib PCR XP plate - can submit LTN Lib PCR XP plates for reISC
