---
# This file contains the configuration for the high throughput genotype by sequencing pipeline.
GBS:
  filters:
    request_type_key: limber_gbs
  relationships:
    GBS-96 Stock: GBS PCR1
    GnT MDA Norm: GBS PCR1
    LANS-96 Lysate: GBS PCR1
    GBS PCR1: GBS PCR2
    GBS PCR2: GBS PCR2 Pool Stock
    GBS PCR2 Pool Stock: GBS PCR Pool
    GBS PCR Pool: GBS PCR Pool Selected
    GBS PCR Pool Selected: GBS MiSeq Pool
