scRNA Core Chromium GEM-X 5p Aggregation:
  pipeline_group: scRNA Core Library Prep
  filters:
    request_type_key: limber_scrna_core_chromium_gem_x_5p_aggregation
  relationships:
    # 2 input routes to this pipeline:
    # LRC GEM-X 5p cDNA PCR XP coming through SeqOps
    # LRC GEM-X 5p cDNA Input coming direct from faculty
    LRC GEM-X 5p cDNA Input: LRC GEM-X 5p Aggregate
    LRC GEM-X 5p cDNA PCR XP: LRC GEM-X 5p Aggregate
    LRC GEM-X 5p Aggregate: LRC GEM-X 5p Cherrypick
scRNA Core Chromium GEM-X 5p:
  pipeline_group: scRNA Core Library Prep
  filters:
    request_type_key: limber_scrna_core_chromium_gem_x_5p
    library_type: Chromium single cell 5 prime GEM-X v3
  library_pass: LBC 5p GEX PCR 2XP
  relationships:
    LRC GEM-X 5p Cherrypick: LRC GEM-X 5p GEX Dil
    LRC GEM-X 5p GEX Dil: LRC GEM-X 5p Frag 2XP
    LRC GEM-X 5p Frag 2XP: LRC GEM-X 5p LigXP
    LRC GEM-X 5p LigXP: LRC GEM-X 5p PCR 2XP
scRNA Core Chromium GEM-X 5p MX:
  pipeline_group: scRNA Core Library Prep
  filters:
    request_type_key: limber_multiplexing
  relationships:
    LRC GEM-X 5p PCR 2XP: LRC GEM-X 5p GLibPS
    LRC GEM-X 5p GLibPS: LRC GEM-X 5p Pool Norm
    LRC GEM-X 5p Pool Norm: LB Lib Pool Norm
