---
# Initial transfer from tube to plate, as entry for one or other of below pipelines. Happens without submissions / requests.
scRNA Core Cell Extraction Entry:
  pipeline_group: scRNA Core Cell Extraction
  relationships:
    LRC Blood Vac: LRC Blood Bank
# scRNA Core Cell Extraction pipeline
scRNA Core Cell Extraction Seq:
  pipeline_group: scRNA Core Cell Extraction
  filters: &scrna_core_cell_extraction_filters
    request_type_key: limber_scrna_core_cell_extraction
  relationships:
    # LRC Blood Vac: LRC Blood Bank
    LRC Blood Bank: LRC PBMC Bank
    LRC PBMC Bank: LRC Bank Seq
scRNA Core Cell Extraction Spare:
  pipeline_group: scRNA Core Cell Extraction
  filters: *scrna_core_cell_extraction_filters
  relationships:
    # LRC Blood Vac: LRC Blood Bank
    LRC Blood Bank: LRC PBMC Bank
    LRC PBMC Bank: LRC Bank Spare
