---
# This is the pipeline configuration for EMSeq
LCM Triomics DNA Prep:
  filters:
    request_type_key: limber_lcm_triomics_dna_prep
  relationships:
    LCMT Lysate: LCMT DNA Adp Lig

LCM Triomics DNA WGS Transition:
  relationships:
    LCMT DNA Adp Lig: LCMT DNA Lib PCR

LCM Triomics DNA EMSeq Transition:
  relationships:
    LCMT DNA Adp Lig: LCMT EM TET2 Ox

LCM Triomics DNA WGS Library Prep:
  filters:
    request_type_key: limber_lcm_triomics_dna_wgs_library_prep
    library_type: LCM Triomics DNA WGS
    relationships:
      LCMT DNA Lib PCR: LCM DNA Lib PCR

LCM Triomics DNA EMSeq Library Prep:
  filters:
    request_type_key: limber_lcm_triomics_dna_emseq_library_prep
    library_type: LCM Triomics DNA EMSeq
  relationships:
    LCMT EM TET2 Ox: LCMT EM TET2 Stop
