---
# This is the pipeline configuration for ANOSPP Lysate preparation.
# It is essentially a straight stamp, no controls added.
ANOSPP Lysate Prep:
  filters:
    request_type_key: limber_anospp_lysis
  library_pass:
    - LANS-96 Lysate
  relationships:
    LANS-96 Stock:: LANS-96 Lysate
