---
# Initial transfer from tube to plate, as entry for below pipeline. Happens without submissions / requests.
scRNA Core Cell Extraction Entry:
  pipeline_group: scRNA Core Cell Extraction Cell Banking
  relationships:
    LRC Blood Vac: LRC Blood Bank
# scRNA Core Cell Extraction pipeline
scRNA Core Cell Extraction Seq:
  pipeline_group: scRNA Core Cell Extraction
  filters:
    request_type_key: limber_scrna_core_cell_extraction_banking
  relationships:
    LRC Blood Vac: LRC Blood Bank
    LRC Blood Bank: LRC PBMC Bank
    LRC PBMC Bank: LRC Bank Seq
scRNA Core Cell Extraction Banking Spare:
  pipeline_group: scRNA Core Cell Extraction Cell Banking
  filters:
    request_type_key: limber_scrna_core_cell_extraction_banking
  relationships:
    LRC PBMC Bank: LRC Bank Spare
