---
# scRNA Core cDNA Prep pipeline configuration.
# Thawing PBMCs and pooling samples from different donors together, then on to
# GEM generation and cDNA prep. Includes faculty input route.
scRNA Core cDNA Prep:
  pipeline_group: scRNA Core cDNA Prep
  filters:
    request_type_key: limber_scrna_core_cdna_prep_v2
    library_type: Chromium single cell 5 prime HT v2
  relationships:
    LRC Bank Seq: LRC PBMC Cryostor
    LRC Bank Spare: LRC PBMC Cryostor
    LRC PBMC Cryostor: LRC PBMC Defrost PBS
    LRC PBMC Defrost PBS: LRC PBMC Pools
    LRC PBMC Pools: LRC HT 5p Chip
    LRC HT 5p Chip: LRC HT 5p GEMs
    LRC HT 5p GEMs: LRC HT 5p cDNA PCR
    LRC HT 5p cDNA PCR: LRC HT 5p cDNA PCR XP
scRNA Core cDNA Prep Input:
  pipeline_group: scRNA Core cDNA Prep
  filters:
    request_type_key: limber_scrna_core_cdna_prep_input
    library_type: Chromium single cell 5 prime HT v2
  relationships:
    LRC PBMC Pools Input: LRC HT 5p Chip
    LRC HT 5p Chip: LRC HT 5p GEMs
    LRC HT 5p GEMs: LRC HT 5p cDNA PCR
    LRC HT 5p cDNA PCR: LRC HT 5p cDNA PCR XP
