---
Kinnex:
  pipeline_group: Kinnex
  filters:
    request_type_key: kinnex_prep
    library_type: RNA Ribo
  library_pass: Kinnex Cherrypick
  relationships:
    LRC GEM-X 5p cDNA PCR XP: Kinnex Cherrypick
    LRC GEM-X 5p cDNA Input: Kinnex Cherrypick
# Then feeds into the standard limber_multiplexing
