---
# Ultima UG200 PCR Free Pipeline
Ultima UG200 High Throughput PCR Free:
  pipeline_group: Ultima UG200 High Throughput PCR Free
  filters:
    request_type_key: limber_ultima_htp_pcr_free
    library_type:
      - Ultima High Throughput PCR Free 96 # same as Ultima
  library_pass: UPF2 Lib XP2
  relationships:
    UPF2 Cherrypicked: UPF2 Shear
    UPF2 Shear: UPF2 Post Shear
    UPF2 Post Shear: UPF2 End Prep
    UPF2 End Prep: UPF2 Lib
    UPF2 Lib: UPF2 Lib XP2
Ultima Multiplexing:
  pipeline_group: Ultima UG200 High Throughput PCR Free
  filters:
    request_type_key:
      - limber_multiplexing_ultima
  relationships:
    UPF2 Lib XP2: UPF2 EqVol Pool
    UPF2 EqVol Pool: UPF2 EqVol Norm
Ultima Balancing:
  pipeline_group: Ultima UG200 High Throughput PCR Free
  relationships:
    UPF2 Lib XP2: UPF2 Balanced Pool
    UPF2 Balanced Pool: UPF2 Balanced Norm
