---
Ultima Conv:
  pipeline_group: Ultima Conv
  filters:
    request_type_key: limber_ultima_conv
  library_pass: Ultima PCR XP
  relationships:
    LBB Lib PCR-XP: Ultima PCR XP

Multiplexing Ultima Conv:
  pipeline_group: Ultima Conv
  filters:
    request_type_key: limber_multiplexing_ultima_conv
  relationships:
    Ultima PCR XP: Ultima PCR XP Norm
    Ultima PCR XP Norm: LBB Lib Pool Stock
    LBB Lib Pool Stock: LB Lib Pool Norm
