---
default: &DEFAULT
  Bioscan_forward_96_v2:
    name: Bioscan_forward_96_v2
    version: 2
    tags:
      - PB1F_bc1001
      - PB1F_bc1002
      - PB1F_bc1003
      - PB1F_bc1004
      - PB1F_bc1005
      - PB1F_bc1006
      - PB1F_bc1007
      - PB1F_bc1008
      - PB1F_bc1009
      - PB1F_bc1010
      - PB1F_bc1011
      - PB1F_bc1012
      - PB1F_bc1013
      - PB1F_bc1014
      - PB1F_bc1015
      - PB1F_bc1016
      - PB1F_bc1017
      - PB1F_bc1018
      - PB1F_bc1019
      - PB1F_bc1020
      - PB1F_bc1021
      - PB1F_bc1022
      - PB1F_bc1023
      - PB1F_bc1024
      - PB1F_bc1025
      - PB1F_bc1026
      - PB1F_bc1027
      - PB1F_bc1028
      - PB1F_bc1029
      - PB1F_bc1030
      - PB1F_bc1031
      - PB1F_bc1032
      - PB1F_bc1033
      - PB1F_bc1034
      - PB1F_bc1035
      - PB1F_bc1036
      - PB1F_bc1037
      - PB1F_bc1038
      - PB1F_bc1039
      - PB1F_bc1040
      - PB1F_bc1041
      - PB1F_bc1042
      - PB1F_bc1043
      - PB1F_bc1044
      - PB1F_bc1045
      - PB1F_bc1046
      - PB1F_bc1047
      - PB1F_bc1048
      - PB1F_bc1049
      - PB1F_bc1050
      - PB1F_bc1051
      - PB1F_bc1052
      - PB1F_bc1053
      - PB1F_bc1054
      - PB1F_bc1055
      - PB1F_bc1056
      - PB1F_bc1057
      - PB1F_bc1058
      - PB1F_bc1059
      - PB1F_bc1060
      - PB1F_bc1061
      - PB1F_bc1062
      - PB1F_bc1063
      - PB1F_bc1064
      - PB1F_bc1065
      - PB1F_bc1066
      - PB1F_bc1067
      - PB1F_bc1068
      - PB1F_bc1069
      - PB1F_bc1070
      - PB1F_bc1071
      - PB1F_bc1072
      - PB1F_bc1073
      - PB1F_bc1074
      - PB1F_bc1075
      - PB1F_bc1076
      - PB1F_bc1077
      - PB1F_bc1078
      - PB1F_bc1079
      - PB1F_bc1080
      - PB1F_bc1081
      - PB1F_bc1082
      - PB1F_bc1083
      - PB1F_bc1084
      - PB1F_bc1085
      - PB1F_bc1086
      - PB1F_bc1087
      - PB1F_bc1088
      - PB1F_bc1089
      - PB1F_bc1090
      - PB1F_bc1091
      - PB1F_bc1092
      - PB1F_bc1093
      - PB1F_bc1094
      - PB1F_bc1095
      - PB1F_bc1096
  Bioscan_reverse_4_1_v2:
    version: 2
    tags:
      - PB1R_bc1097_rc
      - PB1R_bc1098_rc
      - PB1R_bc1099_rc
      - PB1R_bc10100_rc
  Bioscan_reverse_4_2_v2:
    version: 2
    tags:
      - PB1R_bc10101_rc
      - PB1R_bc10102_rc
      - PB1R_bc10103_rc
      - PB1R_bc10104_rc
  Bioscan_reverse_4_3_v2:
    version: 2
    tags:
      - PB1R_bc10105_rc
      - PB1R_bc10106_rc
      - PB1R_bc10107_rc
      - PB1R_bc10108_rc
  Bioscan_reverse_4_4_v2:
    version: 2
    tags:
      - PB1R_bc10109_rc
      - PB1R_bc10110_rc
      - PB1R_bc10111_rc
      - PB1R_bc10112_rc
  Bioscan_reverse_4_5_v2:
    version: 2
    tags:
      - PB1R_bc10113_rc
      - PB1R_bc10114_rc
      - PB1R_bc10115_rc
      - PB1R_bc10116_rc
  Bioscan_reverse_4_6_v2:
    version: 2
    tags:
      - PB1R_bc10117_rc
      - PB1R_bc10118_rc
      - PB1R_bc10119_rc
      - PB1R_bc10120_rc
  Bioscan_reverse_4_7_v2:
    version: 2
    tags:
      - PB1R_bc10121_rc
      - PB1R_bc10122_rc
      - PB1R_bc10123_rc
      - PB1R_bc10124_rc
  Bioscan_reverse_4_8_v2:
    version: 2
    tags:
      - PB1R_bc10125_rc
      - PB1R_bc10126_rc
      - PB1R_bc10127_rc
      - PB1R_bc10128_rc
  Bioscan_reverse_4_9_v2:
    version: 2
    tags:
      - PB1R_bc10129_rc
      - PB1R_bc10130_rc
      - PB1R_bc10131_rc
      - PB1R_bc10132_rc
  Bioscan_reverse_4_10_v2:
    version: 2
    tags:
      - PB1R_bc10133_rc
      - PB1R_bc10134_rc
      - PB1R_bc10135_rc
      - PB1R_bc10136_rc
  Bioscan_reverse_4_11_v2:
    version: 2
    tags:
      - PB1R_bc10137_rc
      - PB1R_bc10138_rc
      - PB1R_bc10139_rc
      - PB1R_bc10140_rc
  Bioscan_reverse_4_12_v2:
    version: 2
    tags:
      - PB1R_bc10141_rc
      - PB1R_bc10142_rc
      - PB1R_bc10143_rc
      - PB1R_bc10144_rc
  Bioscan_reverse_4_13_v2:
    version: 2
    tags:
      - PB1R_bc10145_rc
      - PB1R_bc10146_rc
      - PB1R_bc10147_rc
      - PB1R_bc10148_rc
  Bioscan_reverse_4_14_v2:
    version: 2
    tags:
      - PB1R_bc10149_rc
      - PB1R_bc10150_rc
      - PB1R_bc10151_rc
      - PB1R_bc10152_rc
  Bioscan_reverse_4_15_v2:
    version: 2
    tags:
      - PB1R_bc10153_rc
      - PB1R_bc10154_rc
      - PB1R_bc10155_rc
      - PB1R_bc10156_rc
  Bioscan_reverse_4_16_v2:
    version: 2
    tags:
      - PB1R_bc10157_rc
      - PB1R_bc10158_rc
      - PB1R_bc10159_rc
      - PB1R_bc10160_rc
  Bioscan_reverse_4_17_v2:
    version: 2
    tags:
      - PB1R_bc10161_rc
      - PB1R_bc10162_rc
      - PB1R_bc10163_rc
      - PB1R_bc10164_rc
  Bioscan_reverse_4_18_v2:
    version: 2
    tags:
      - PB1R_bc10165_rc
      - PB1R_bc10166_rc
      - PB1R_bc10167_rc
      - PB1R_bc10168_rc
  Bioscan_reverse_4_19_v2:
    version: 2
    tags:
      - PB1R_bc10169_rc
      - PB1R_bc10170_rc
      - PB1R_bc10171_rc
      - PB1R_bc10172_rc
  Bioscan_reverse_4_20_v2:
    version: 2
    tags:
      - PB1R_bc10173_rc
      - PB1R_bc10174_rc
      - PB1R_bc10175_rc
      - PB1R_bc10176_rc
  Bioscan_reverse_4_21_v2:
    version: 2
    tags:
      - PB1R_bc10177_rc
      - PB1R_bc10178_rc
      - PB1R_bc10179_rc
      - PB1R_bc10180_rc
  Bioscan_reverse_4_22_v2:
    version: 2
    tags:
      - PB1R_bc10181_rc
      - PB1R_bc10182_rc
      - PB1R_bc10183_rc
      - PB1R_bc10184_rc
  Bioscan_reverse_4_23_v2:
    version: 2
    tags:
      - PB1R_bc10185_rc
      - PB1R_bc10186_rc
      - PB1R_bc10187_rc
      - PB1R_bc10188_rc
  Bioscan_reverse_4_24_v2:
    version: 2
    tags:
      - PB1R_bc10189_rc
      - PB1R_bc10190_rc
      - PB1R_bc10191_rc
      - PB1R_bc10192_rc

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT
