---
:searches: {}
:transfer_templates: {}
:printers:
  limit: 5
  default_count: 2
:purposes: {}
:purpose_uuids: {}
:robots: {}
:default_pmb_templates: {}
:default_sprint_templates: {}
:default_printer_type_names: []
:submission_templates: {}
:qc_purposes: []
:locations: {}
:pipelines: {}
:poolings: {}