name: Build and release

on:
  release:
    types: published

env:
  BUNDLE_WITHOUT: 'test lint'

jobs:
  build-and-release:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      # Actually run our build
      - name: Compile Build
        run: ./compile-build

      - name: Release Build
        uses: sanger/.github/.github/actions/release/upload-release@master
        with:
          upload_url: ${{ github.event.release.upload_url }}


