name: Test compilation

on:
  - push
  - pull_request

env:
  BUNDLE_WITHOUT: 'test lint'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      # Actually run our build
      - name: Create Build
        run: ./compile-build

      # Create a release tag based on the branch name and .release-version file
      - name: Set release tag
        # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        # On the develop branch this might create RELEASE_VERSION=2.4.6-987654321-develop
        # On the master branch this would then only create RELEASE_VERSION=2.4.6
        run: echo "RELEASE_VERSION=$(printf -- '%s%s\n' $(cat .release-version) $([ ${BRANCH_NAME} = "develop" ] && printf -- '-%s-develop' ${GITHUB_RUN_ID} || echo ""))" >> $GITHUB_ENV

    # Do not actually save build or create release itself
