name: Test compilation

on:
  push:
    branches:
      - y25-107-6-migrate-actions

env:
  BUNDLE_WITHOUT: 'test lint'
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      # Actually run our build
      - name: Create Build
        run: ./compile-build

      - name: Get release version
        run: echo "RELEASE_VERSION=$(cat .release-version)" >> "$GITHUB_ENV"

      # Create a release tag based on the branch name and .release-version file
      - name: Set release tag
        uses: sanger/.github/.github/actions/release/set-release-tag@master
        with:
          branch_name: ${{ env.BRANCH_NAME }}
          release_version: ${{ env.RELEASE_VERSION }}
          github_run_id: ${{ github.run_id }}

    # Do not actually save build or create release itself
