name: Create/Update merge to master pull request for production releases

on:
  push:
    branches:
      - develop
      - sh51/create-release-pr-action
jobs:
  create_update_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create pull request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up \
            --base master \
            --head develop \
            --title "Merge Develop into Master" \
            --fill # Fill in the body with the commit messages
