name: Javascript testing

on:
  - push
  - pull_request

env:
  TZ: Europe/London

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Node Information
        run: node --version
      - name: Install
        run: yarn install
      - name: Run yarn test
        run: yarn test
