name: Lint

env:
  BUNDLE_WITHOUT: 'test development default'

on:
  push:
  pull_request:
    types:
      # defaults
      - opened
      - synchronize
      - reopened
      # custom
      - ready_for_review # required for Github-created PRs

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Setup yarn
        run: yarn install

      - name: Run prettier
        run: yarn prettier --check .

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Setup yarn
        run: yarn install

      - name: Run lint
        run: bundle exec rubocop --extra-details --display-style-guide --parallel

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Setup yarn
        run: yarn install

      - name: Run ESLint
        run: yarn lint

  erb_lint:
    name: ERB Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Setup yarn
        run: yarn install

      - name: Run ERB Lint
        run: bundle exec erb_lint --format json --lint-all
