name: Javascript testing

on:
  - push
  - pull_request

jobs:
  js_test: # note: this name is referenced in upload_coverage.yml
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Node Information
        run: node --version
      - name: Install
        run: yarn install
      - name: Run yarn test
        run: yarn test
      - name: Cache test coverage
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/app/javascript/coverage/lcov.info
          key: coverage-js-cache-${{ github.sha }}
