name: Unit tests

on:
  # Warning: changing run conditions could prevent coverage report in PR, see codecov.yml for `after_n_builds`
  push:
  pull_request:

jobs:
  js_test:
    name: Javascript tests
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Node Information
        run: node --version

      - name: Setup yarn
        run: yarn install

      - name: Run yarn test
        run: yarn coverage

      - name: Upload coverage reports to Codecov
        uses: sanger/.github/.github/actions/tests/codecov@master
        with:
          name: ${{ github.run_id }}_${{ github.job }}_${{ github.event_name }}
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: javascript,${{ github.event_name }}
          disable-search: true
          files: ${{ github.workspace }}/app/frontend/coverage/lcov.info
