name: Javascript testing

on:
  - push
  - pull_request

jobs:
  js_test:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Node Information
        run: node --version
      - name: Install
        run: yarn install
      - name: Run yarn test
        run: yarn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: javascript,${{ github.event_name }}
          fail_ci_if_error: true
          disable_search: true
          files: ${{ github.workspace }}/app/javascript/coverage/lcov.info
          # Note: see codecov.yml for more additional settings
