name: Ruby RSpec Tests

on:
  # Warning: changing run conditions could prevent coverage report in PR, see codecov.yml for `after_n_builds`
  - push
  - pull_request

env:
  BUNDLE_WITHOUT: 'development lint'

jobs:
  rspec_tests:
    name: RSpec Ruby tests
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - name: Checkout Repository
        uses: sanger/.github/.github/actions/setup/checkout@master

      - name: Setup Ruby
        uses: sanger/.github/.github/actions/setup/ruby@master

      - name: Setup Node
        uses: sanger/.github/.github/actions/setup/node@master

      - name: Setup stable Chrome
        uses: sanger/.github/.github/actions/tests/setup-chrome@master
        with:
          chrome-version: 128
          install-chromedriver: true
          install-dependencies: true

      - name: Additional setup
        run: bin/setup

      - name: Run rspec
        run: bundle exec rspec

      - name: Publish code coverage to Code Climate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID || '1735fdb62543d410c5ed4469e402641a7986f1ebf62ff7398f3ab8ccc98069ef' }}
      
      - name: Upload coverage reports to Codecov
        uses: sanger/.github/.github/actions/tests/codecov@master
        with:
          name: ${{ github.run_id }}_${{ github.job }}_${{ github.event_name }}
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ruby,${{ github.event_name }}
          disable_search: true
          files: ${{ github.workspace }}/lcov.info
