name: Javascript testing

on:
  - push
  - pull_request

jobs:
  js_test: # note: this name is referenced in upload_coverage.yml
    runs-on: ubuntu-latest
    env:
      TZ: Europe/London

    steps:
      - uses: actions/checkout@v2
      - name: Export node version
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - name: Node Information
        run: node --version
      - name: Install
        run: yarn install
      - name: Run yarn test
        run: yarn test
