name: Upload Coverage

on:
  - push
  - pull_request

env:
  TZ: Europe/London

jobs:
  upload_coverage:
    name: Upload test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Ruby tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'ruby_test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for JS tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'js_test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Perform the upload
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID || '1735fdb62543d410c5ed4469e402641a7986f1ebf62ff7398f3ab8ccc98069ef' }}
        with:
          coverageLocations: |
            ${{github.workspace}}/lcov.info:lcov # Ruby
            ${{github.workspace}}/app/javascript/coverage/lcov.info:lcov # JavaScript
